### ISSUE TITLE
setup.py missing requirements

### ISSUE THREAD

**Issue by schwehr** [secdev/scapy#68] opened 2016-02-22 06:42 UTC
This demonstrates the issue (typed by hand, so sorry if there are typos):

```
virtualenv ve
source ve/bin/activate
pip install scapy
pip install jupyter # IPython and notebooks
ipython
from scapy.all import *
# error about missing pcapy
# exit ipython
pip install pcapy
ipython
from scapy.all import *
# error about dnet
ipython
In [1]: from scapy.all import *
WARNING: No route found for IPv6 destination :: (no default route?)
In [2]:
```

scapy needs pcapy and dnet in it's requirements so that pip install scapy makes sure that pcapy and dnet are installed if they are not already there.

**Comment by guedou** [comment] 2016-02-22 08:11
In order to helps use reproduce the issue, could you specify your environment ? (OS/Distribution & version)

Thanks,
Guillaume

**Comment by schwehr** [comment] 2016-02-22 14:32
Looks like the setup changes based on os.  Definitely happens on macosx with a clean python setup.  ( e.g. no prior sudo installs as mentioned in #69 ).  Looking in arch/, it might happen in other BSD derived systems.  The linux.py does not import the same modules and I don't see the issue on Ubuntu 14.04.

On the mac, it happens for me with the system python and with python from fink.

**Comment by guedou** [comment] 2016-02-27 09:30
Thanks for your explanation.

I am not an OS X user, so I won't be able to propose an efficient patch myself. Last time that I checked, this point proves to be tricky ... If you provide a PR, I will try to test it on a friend OS X.

Alternatively, I am in the process of cleaning scapy-bpf and porting it to Scapy 2. BSD derivatives will all be supported by default without the mandatory need of the pcap and dnet modules. Scapy will however by slightly slower.

**Comment by AmedeoSapio** [comment] 2016-04-06 11:36
Every time I run:
`from scapy.all import *`

I see:

> WARNING: can't import layer ipsec: No module named Crypto.Util.number

This seems to be related to this issue. Since  bf4c2e8a58852cdb2e1d153fc951c481a23c9488 PyCrypto is required, so maybe setup.py should reference it as a requirement.

I am using Linux Fedora 21, the last version of scapy cloned from the repo and installed with 

`python setup.py install`

**Comment by p-l-** [comment] 2016-04-07 06:14
@AmedeoSapio PyCrypto is not a requirement since Scapy will (or should, at least) work without it (even though some features won't work, obviously).

**Comment by gpotter2** [comment] 2016-12-18 17:54
@p-l- As we are going to get rid of pycrypto, we can close this.

**Closed** 2016-12-18 18:18 UTC
