### ISSUE TITLE
netflow v9 DataFlowSet length with padding

### ISSUE THREAD

**Issue by preet** [secdev/scapy#1758] opened 2018-12-23 19:28 UTC
The current implementation of NetflowDataflowsetV9 in the netflow layer does not seem to take padding bytes into account as is recommended by the spec (https://www.ietf.org/rfc/rfc3954.txt):

>    Padding
>          The Exporter SHOULD insert some padding bytes so that the
>          subsequent FlowSet starts at a 4-byte aligned boundary.  It is
>          important to note that the Length field includes the padding
>          bytes.  Padding SHOULD be using zeros.

In scapy/layers/netflow.py:
```python
class NetflowDataflowsetV9(Packet):
    name = "Netflow DataFlowSet V9"
    fields_desc = [ShortField("templateID", 255),
                   FieldLenField("length", None, length_of="records", adjust=lambda pkt, x:x + 4),  # noqa: E501
                   PadField(PacketListField("records", [], NetflowRecordV9,
                                            length_from=lambda pkt: pkt.length - 4),  # noqa: E501
4, padwith=b"\x00")]
```

I'm not sure what the best way to set the length to include padding bytes is. I think one way is to set the 'adjust' function in FieldLenField to be something like:

```python
def adj_len(pkt, x):
    x += 4
    if (x % 4) > 0:
        x = (x/4 + 1)*4
    return x
```

**Comment by p-l-** [comment] 2018-12-24 08:50
I don't have time for now to dive into this issue, but:
    * You should use `//` in `adj_len()`. Also, as you do not use `pkt`, use `_`.
    * If you need a `lambda` version of your function, you can use: `lambda _, x: (x // 4 + 2) * 4 if x % 4 else x + 4`

**Comment by p-l-** [comment] 2018-12-25 11:09
Actually, I think the `PadField()` does just what the RFC says: it insert null bytes as padding, to align the length of `records` to four bytes. Or did I miss something?

**Comment by gpotter2** [comment] 2018-12-25 14:05
@p-l- The issue is that the `FieldLenField` doesn’t take the padding into account when building. We should use the `post_build` method

**Comment by p-l-** [comment] 2018-12-25 17:04
@gpotter2 in that case, a correct fix could be to actually use `adjust`, as suggested by @preet.

@preet could you provide (as suggested by the issue template I think) an example of code, with the current result and the expected result?

**Comment by gpotter2** [comment] 2018-12-25 17:19
Fair enough !

Note that you can use fancy negative modulos to shorten the function:
![c0347e89-c5f9-4f10-a3c4-ed3be9c4a19f](https://user-images.githubusercontent.com/10530980/50425177-92e02300-0871-11e9-9823-120f7e38c662.jpeg)

**Comment by gpotter2** [comment] 2019-01-20 15:10
Fixed in https://github.com/secdev/scapy/issues/1795

**Closed as completed** 2019-01-28 10:25 UTC
Labels: bug
