### ISSUE TITLE
Scapy - Unable to send TCP packets to multiple destinations from same source

### ISSUE THREAD

**Issue by cswarnan** [secdev/scapy#565] opened 2017-03-16 20:29 UTC
Hi
I am writing a program to send payload to multiple IP addresses:

data = "A"*1460
ans, un_ans = sr(IP(src="192.21.1.135", dst="192.21.1.4") / TCP()/data)
ans.show()
time.sleep(2)
ans, un_ans = sr(IP(src="192.21.1.135", dst="192.21.1.6") / TCP()/data)
ans.show()

I am getting my console output as below:
Get-NetRoute : The term 'Get-NetRoute' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

Get-NetRoute -AddressFamily IPV6 | select ifIndex, DestinationPrefix, NextHop
  + CategoryInfo          : ObjectNotFound: (Get-NetRoute:String) [], Comman 
 dNotFoundException
  + FullyQualifiedErrorId : CommandNotFoundException

Get-NetRoute : The term 'Get-NetRoute' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

Get-NetRoute -AddressFamily IPV6 | select ifIndex, DestinationPrefix
  + CategoryInfo          : ObjectNotFound: (Get-NetRoute:String) [], Comman 
 dNotFoundException
  + FullyQualifiedErrorId : CommandNotFoundException

Begin emission:
Finished to send 1 packets.
.............................................................................................................................................................................................

However if I use ICMP() then it does execute properly.

I am on wired network. Environment is Windows 7 and Python27 with Scapy dev

**Comment by gpotter2** [comment] 2017-03-18 22:36
Please close this, duplicate of https://github.com/secdev/scapy/issues/562

**Closed** 2017-03-19 12:16 UTC
