### ISSUE TITLE
scapy sniffing less packets than wireshark

### ISSUE THREAD

**Issue by TraverseBiTree** [secdev/scapy#3236] opened 2021-05-29 13:06 UTC
-   Scapy version: 2.4.5
-   Python version: 3.9
-   Operating System: Windows 10

Source code sniffing packets with scapy is here:
```python
from scapy.all import *


def pack_callback(pkt: scapy.packet.Packet):
    global g_count
    print(g_count)
    g_count += 1
    time.sleep(0.05)    # Simulate the time spent processing tasks


if __name__ == '__main__':
    g_count = 0
    sniff(prn=pack_callback, iface="Realtek PCIe GbE Family Controller", count=0)
```

![image](https://user-images.githubusercontent.com/30373236/120071372-91118e00-c0c1-11eb-9cdc-8e2f010e6e9f.png)
![image](https://user-images.githubusercontent.com/30373236/120071375-966ed880-c0c1-11eb-8616-cf6810fad313.png)

I use a `sleep()` function to simulate the time spent processing tasks in `callback` function.
both **scapy** and **wireshark** start at the same time.
Obviously see **scapy** cautions _less_ packet than **wireshark** . How can I catch all packets using scapy without any packet loss.

**Comment by guedou** [comment] 2021-05-29 16:11
Duplicate of gitter question.

**Closed by guedou** 2021-05-29 16:11 UTC
