### ISSUE TITLE
Filter not working in Windows 10

### ISSUE THREAD

**Issue by GasparCheng** [secdev/scapy#2020] opened 2019-05-08 14:03 UTC
#### Symptoms

* Can't filter ICMP packets
* But scapy.sniff() can
```
PS C:\Users\Gaspar\Documents\TestPlatform> .\.venv\Scripts\activate.ps1
(.venv) PS C:\Users\Gaspar\Documents\TestPlatform> python
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import scapy.all as scapy
>>> scapy.sniff(filter='icmp')
<Sniffed: TCP:0 UDP:0 ICMP:0 Other:0>                      <--- Filter not working
>>> scapy.sniff()
<Sniffed: TCP:19 UDP:329 ICMP:6 Other:116>            <--- Without filter, get ICMP packets
>>> scapy.sniff(filter='icmp')
<Sniffed: TCP:0 UDP:0 ICMP:0 Other:0>
```

#### Environment

-   Scapy version: `2.4.2`
-   Python version: `3.6.5`
-   Operating System: `Windows 10`

**Comment by gpotter2** [comment] 2019-05-11 19:35
I can't reproduce

**Comment by guedou** [comment] 2019-05-30 07:48
Did you install `windump`?

**Comment by gpotter2** [comment] 2019-06-01 14:49
`windump` shouldn't be required on live sniffing (only on offline). However I cannot reproduce :/

**Comment by guedou** [comment] 2019-06-07 07:32
I am closing the issue due to no reply from the reporter. Please reopen and test with current master.

**Closed by guedou** 2019-06-07 07:32 UTC
Labels: needs additional info
