### ISSUE TITLE
Is there a place to see what is the current roadmap?

### ISSUE THREAD

**Issue by cbene06** [secdev/scapy#87] opened 2016-03-15 13:36 UTC
Hi,

I'd like to contribute and help in building a new feature. Is there a roadmap or/and any forum where we can discuss about it?

Thanks,
Christophe

**Comment by p-l-** [comment] 2016-03-15 15:46
Hi,

Glad to hear that, thanks for your interest in Scapy!

Maybe the best place to start is to open an issue mentioning the improvement / new feature you would like to contribute to track this?

**Comment by cbene06** [comment] 2016-03-15 16:18
Hi Pierre,

I don't have improvement or new feature I would like to contribute yet; in fact it was the aim of my question ;-)

I would like to know if there is sleeping or ongoing development that requires resource, if that the case I would love to be part of it!

thanks,
Christophe.

----- Mail original -----
De: "Pierre Lalet" <notifications@github.com>
À: "secdev/scapy" <scapy@noreply.github.com>
Cc: "cbene06" <cbenejean@free.fr>
Envoyé: Mardi 15 Mars 2016 16:46:11
Objet: Re: [scapy] Question: Is there a place to see what is the current roadmap? (#87)



Hi, 

Glad to hear that, thanks for your interest in Scapy! 

Maybe the best place to start is to open an issue mentioning the improvement / new feature you would like to contribute to track this?

**Comment by p-l-** [comment] 2016-03-15 17:34
Hi,

Nothing specific comes to my mind for now, but we'll open an issue if/when we have an idea (cc @guedou @phil777).

New protocols are always interesting and appreciated, and so are new high-level functions (like `traceroute()`).

**Comment by guedou** [comment] 2016-03-15 18:57
Since Philippe asked us to maintain Scapy, our main tasks were mainly to fix issues. Therefore, there is no such thing as a roadmap. Due to the move to github, things seems to evolve differently as we get more and more contributors. A roadmap might indeed be a good idea =)

In the meantime, I have some ideas in mind. Most of them involve improving the documentation. This is an import task, as this the main entry point to gather more users.
1. add unit tests to protocols in contrib/ Some of them don't have any test. This is problematic when we make changes to the core;
2. check that the documentation is still up to date with the code;
3. move examples from Scapy presentations to the documentation. According to some recent discussions I had, it seems that they are no synced.

**Comment by kinap** [comment] 2016-03-16 03:23
Hi Christophe,

I'm not a part of the secdev team / maintainers, but some things I planned on submitting a pull request for in the next few months:

1. ChaCha20-Poly1305 (CCP) algorithm support to the IPSec layer. Requires contributing to pycrypto probably.
2. unit tests for AEAD algorithms in IPSec layer (AES-GCM, AES-CCM, CCP).

Thanks,
Dan

**Comment by cbene06** [comment] 2016-03-16 09:31
Thanks all for your answers. I'm ok also to work on bug fixes, specially when I'm starting to contribute. I don't see a lot of bugs opened right now however, right?

Regards,
Christophe

----- Mail original -----
De: "Daniel Collins" <notifications@github.com>
À: "secdev/scapy" <scapy@noreply.github.com>
Cc: "cbene06" <cbenejean@free.fr>
Envoyé: Mercredi 16 Mars 2016 04:23:40
Objet: Re: [scapy] Question: Is there a place to see what is the current roadmap? (#87)



Hi Christophe, 

I'm not a part of the secdev team / maintainers, but some things I planned on submitting a pull request for in the next few months: 

    1. ChaCha20-Poly1305 (CCP) algorithm support to the IPSec layer. Requires contributing to pycrypto probably. 
    2. unit tests for AEAD algorithms in IPSec layer (AES-GCM, AES-CCM, CCP). 


Thanks, 
Dan

**Comment by guedou** [comment] 2016-03-16 16:25
We did not yet fix everything that was reported on bitbucket https://bitbucket.org/secdev/scapy/wiki/Home

To start, it will be really cool if you could move pending bitbucket PR to github after contacting their authors.

**Comment by cbene06** [comment] 2016-03-17 09:00
ok I will start with that. I suppose I should contact only the owner of unassigned PR, right?

----- Mail original -----
De: "Guillaume Valadon" <notifications@github.com>
À: "secdev/scapy" <scapy@noreply.github.com>
Cc: "cbene06" <cbenejean@free.fr>
Envoyé: Mercredi 16 Mars 2016 17:25:10
Objet: Re: [scapy] Question: Is there a place to see what is the current roadmap? (#87)



We did not yet fix everything that was reported on bitbucket https://bitbucket.org/secdev/scapy/wiki/Home 

To start, it will be really cool if you could move pending bitbucket PR to github after contacting their authors.

**Comment by cbene06** [comment] 2016-03-17 10:31
I saw there is tools to make it, for example: https://github.com/jeffwidman/bitbucket-issue-migration

I will make a try if you all agree. 

Thanks

----- Mail original -----
De: "Guillaume Valadon" <notifications@github.com>
À: "secdev/scapy" <scapy@noreply.github.com>
Cc: "cbene06" <cbenejean@free.fr>
Envoyé: Mercredi 16 Mars 2016 17:25:10
Objet: Re: [scapy] Question: Is there a place to see what is the current roadmap? (#87)



We did not yet fix everything that was reported on bitbucket https://bitbucket.org/secdev/scapy/wiki/Home 

To start, it will be really cool if you could move pending bitbucket PR to github after contacting their authors.

**Comment by guedou** [comment] 2016-03-17 15:14
@cbene06 Sorry I realize that I did not clearly write what I expected.

Concerning BB issues, I think that it is better to leave them on BB. A lot of them were created on trac before migrating to BB. Therefore, I believe that most of them are irrelevant today. 
On the other hand, you can have  a look at "new" (until 2012) BB issues, reproduce them, then close them on BB, or fix them via a github PR.

Concerning BB pull-requests, I think that the best is to contact their authors on BB and inform them that Scapy moved to github. You can inform them, that they can submit a new PR on github or you can do it for them. Please keep their name & email adress in the commit message if you do so.

Thanks a lot for your help.

**Comment by ajstein** [comment] 2016-03-20 17:32
Well I am coming here after seeing #92 was closed.  Is there any progress on migrating Bitbucket issues?  Is there anything else a noivce can do with documentation to help out?

**Comment by p-l-** [comment] 2016-03-20 18:02
@ajstein that's the good place!

As @guedou said, we do not want to automatically migrate issues from Bitbucket, since some (most?) of them have been abandoned by their author or are no longer valid.

If you find a issue there that **is** valid for you, you can open an issue here, link it to the original issue on Bitbucket (that you can close, referencing the issue on Github).

As I mentioned in a previous comment, "new protocols are always interesting and appreciated, and so are new high-level functions (like `traceroute()`)."

**Comment by ajstein** [comment] 2016-03-20 18:05
So, in response to your points:

- My Python skills are weak after a long hiatus.  I am trying to get back to it.  I will think about something traceroute.  Sounds like an interesting start.

- In the meantime, I will review Bitbucket issues and see what I can find.

**Comment by p-l-** [comment] 2016-03-20 18:33
@ajstein `traceroute()` already exists.

**Comment by ajstein** [comment] 2016-03-20 18:35
Sorry, I should not speak so loosely.  I obviously have not reviewed the code so deeply.  I am looking at Bitbucket for inspiration for easier stuff.  Then I will work my way up if possible.

**Comment by p-l-** [comment] 2016-03-20 18:40
No problem, I just wanted to make sure you wouldn't start writing something that already exists. Good luck and don't hesitate to ask for help / advise.

**Comment by irl** [comment] 2016-09-24 19:39
From the perspective of Debian, I've noticed that a lot of the files in Scapy do not have clear licensing or copyright notices. Please keep in mind for future development that simply copying and pasting code chunks from bug trackers may be easy, but it creates work for others, that may lead to that code simply not being shipped in the Debian package.

**Comment by guedou** [comment] 2016-09-27 12:45
@irl could you be more specific and provide examples of what should be done or not done to make Debian maintainers life easier ? Thanks.

**Comment by irl** [comment] 2016-09-27 13:01
@guedou Clear copyright notices, that state the year, copyright owner and the license grant. This can be per file if everyone wants to contribute and have different licenses but this leads to futher problems. For example, you have GPL-2 and GPL-3 code, which cannot work together. The GPL-2 code must be GPL-2 forever because the "or at your option, any later version" was not added in the license grant, and the GPL-3+ code even with the "or at your option" clause cannot be compatible with GPL-2. Licensing is a nightmare.

**Comment by geofurb** [comment] 2016-10-31 21:39
Is porting Scapy to Python 3.x something that might be reconsidered since discontinuation of Python 2.5 support?

**Comment by irl** [comment] 2016-10-31 21:49
@geofurb https://github.com/phaethon/scapy is a port of Scapy to Python 3, and I've packaged this in Debian as [python3-scapy](https://packages.debian.org/search?suite=stretch&keywords=python3-scapy) though I would love to see these changes merged into a Py2/Py3/PyPy all-in-one source to be able to build all three Debian packages from the same source package as is done with basically every other Python package (at least for Py2/Py3).

**Comment by geofurb** [comment] 2016-10-31 22:01
@irl I'm equally happy to use Scapy3k, I'm just hesitant because I'm not sure what the differences are between the latest version of each. (I know strings vs bytes is a big deal somewhere in all of this, but I'm not sure about specifics and what else might be changed.)

**Comment by irl** [comment] 2016-10-31 22:59
It's mostly strings vs bytes. I'm not entirely sure if Scapy3k is being kept in sync with Scapy with a view to merging or if it's just a plain fork though.

**Comment by guedou** [comment] 2016-11-03 09:24
Porting the current codebase to Python 3 is currently not on our roadmap. We believe that it more important to invest in a new Scapy rewrite. A prototype is available at: [https://bitbucket.org/secdev/scapy3-prototype2](https://bitbucket.org/secdev/scapy3-prototype2). If you fill like it, we could also discuss guidelines that will ease porting to Python 3.

**Comment by gpotter2** [comment] 2016-12-18 15:27
Hello,
Here is a TODO list from what i've found in scapy's code:
- Add IPOptionRR randval support [here](https://github.com/secdev/scapy/blob/45c59302cefa364f6584710f9116f8492e3bdcc6/scapy/layers/inet.py#L307)
- Remove the "trick" from [carp.py](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/contrib/carp.py#L47)
- Add support to IPv6 addresses other than Ethernet in [dhcp6.py](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/layers/dhcp6.py#L204) and in [route.py](https://github.com/secdev/scapy/blob/32d71796e808aeed2e9668e6248013b2f35d3e5b/scapy/route.py#L148)
- Better instanciation of ASN1F_field in [asn1fields.py]( https://github.com/secdev/scapy/blob/a6e4ab2a45fe5e5bb9b4b15f78ebc4f1778be6b3/scapy/asn1fields.py#L475)
- BPF kernel pointer in [linux.py](https://github.com/secdev/scapy/blob/7ecb14818154254a846b047727b2fb29055c8254/scapy/arch/linux.py#L150)
- Support other distributions than linux when not fully available in route6.py [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/route6.py#L223) and [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/route6.py#L240)
- Support Teredo's route in [route6.py](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/route6.py#L41)
- Improve route6.py make_route to be more precise [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/route6.py#L76)
- Fix cdp.py [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/contrib/cdp.py#L216) and [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/contrib/cdp.py#L245)
- Fix ByteField/BitField in inet6.py [here](https://github.com/secdev/scapy/blob/35f97efc53839f6366918c251dba5df2ac553c8d/scapy/layers/inet6.py#L378)
- Fix a bug with ICMPv6 in inet6.py [here](https://github.com/secdev/scapy/blob/35f97efc53839f6366918c251dba5df2ac553c8d/scapy/layers/inet6.py#L424)
- Support authdata in [ospf.py](https://github.com/secdev/scapy/blob/f912538b7959a68ad83e7f18eee57cd5a8aef7df/scapy/contrib/ospf.py#L68)
- Remove some data from payload in ospf.py in post_build function : [here](https://github.com/secdev/scapy/blob/f912538b7959a68ad83e7f18eee57cd5a8aef7df/scapy/contrib/ospf.py#L71)
- Define refference in dhcp6.py [here](https://github.com/secdev/scapy/blob/c6e1e6ccd201664db20068c0aaabba83082ea449/scapy/layers/dhcp6.py#L304)
- Add encoding for dhcp6 auth like [decoding](https://github.com/secdev/scapy/blob/c6e1e6ccd201664db20068c0aaabba83082ea449/scapy/layers/dhcp6.py#L485)
- Integrate Unique local Address in utils6.py [here](https://github.com/secdev/scapy/blob/c6e1e6ccd201664db20068c0aaabba83082ea449/scapy/utils6.py#L191)
- Finish commenting in6_ifaceidtomac in utils6.py [here](https://github.com/secdev/scapy/blob/c6e1e6ccd201664db20068c0aaabba83082ea449/scapy/utils6.py#L242)
-  See TODO in igmp.py [here](https://github.com/secdev/scapy/blob/c6e1e6ccd201664db20068c0aaabba83082ea449/scapy/contrib/igmp.py#L7)
- Dynamically allocate sufficient size in isis.py [here](https://github.com/secdev/scapy/blob/f912538b7959a68ad83e7f18eee57cd5a8aef7df/scapy/contrib/isis.py#L592)
- Check options in p0f.py [here](https://github.com/secdev/scapy/blob/8e08beeab81183b3bb02bf5c62f5100bcaede555/scapy/modules/p0f.py#L386)
- See TODO in p0f.py [here](https://github.com/secdev/scapy/blob/8e08beeab81183b3bb02bf5c62f5100bcaede555/scapy/modules/p0f.py#L520)
- Merge IGMPv3 packet Bindlayers in igmpv3.py [here](https://github.com/secdev/scapy/blob/c6e1e6ccd201664db20068c0aaabba83082ea449/scapy/contrib/igmpv3.py#L19)
- Implement serial specific function codes in [modbus.py](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/contrib/modbus.py#L23)
- Add FIFOCount to ByteCount (modbus.py) [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/contrib/modbus.py#L489)
- Complete list of Padding in HomePlugAV.py [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/contrib/HomePlugAV.py#L133)
- Complete FragmentCond [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/contrib/HomePlugAV.py#L138)
- distinguish IKEv1/IKEv2 in ikev2.py [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/contrib/ikev2.py#L444)
- See TODO in inet.py [here](https://github.com/secdev/scapy/blob/45c59302cefa364f6584710f9116f8492e3bdcc6/scapy/layers/inet.py#L1628)
- Add regression tests in regression.uts as said [here](https://github.com/secdev/scapy/blob/45c59302cefa364f6584710f9116f8492e3bdcc6/test/regression.uts#L1692)
- Do in regression.uts [this](https://github.com/secdev/scapy/blob/45c59302cefa364f6584710f9116f8492e3bdcc6/test/regression.uts#L3264)
- Use "with" in main.py [here](https://github.com/secdev/scapy/blob/6d9e1a2f1a6f2511e3457ded6e914104106f362f/scapy/main.py#L308)
- Fix missing check in inet6.py [here](https://github.com/secdev/scapy/blob/35f97efc53839f6366918c251dba5df2ac553c8d/scapy/layers/inet6.py#L445)
- Test scope matching in [inet6.py] [here](https://github.com/secdev/scapy/blob/35f97efc53839f6366918c251dba5df2ac553c8d/scapy/layers/inet6.py#L466)
- Factorise in asn1.py [here](https://github.com/secdev/scapy/blob/a6e4ab2a45fe5e5bb9b4b15f78ebc4f1778be6b3/scapy/asn1/asn1.py#L113)
- Use flag "field" in isakmp.py [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/layers/isakmp.py#L185)
- Support special sets in volatile.py [here](https://github.com/secdev/scapy/blob/c6e1e6ccd201664db20068c0aaabba83082ea449/scapy/volatile.py#L347)
- Provide update() in pkcs1.py [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/layers/tls/crypto/pkcs1.py#L99)
- See this in pkcs1.py [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/layers/tls/crypto/pkcs1.py#L332)
- Finish X509.py [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/layers/x509.py#L199)
- Encapsulate RSA keys in x509.py [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/layers/x509.py#L728)
- Use from_public_point in cert.py [here](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/layers/tls/cert.py#L265)
- Fill fields in l2.py [here](https://github.com/secdev/scapy/blob/35f97efc53839f6366918c251dba5df2ac553c8d/scapy/layers/l2.py#L208)
- Fix ospf.py [here](https://github.com/secdev/scapy/blob/f912538b7959a68ad83e7f18eee57cd5a8aef7df/scapy/contrib/ospf.py#L259)
- See [this](https://github.com/secdev/scapy/blob/e30c0525f025f2b05b3e9d26dbce2627d15cc720/scapy/fields.py#L655) in fields.py
- Something to do [here](https://github.com/secdev/scapy/blob/c6e1e6ccd201664db20068c0aaabba83082ea449/scapy/packet.py#L480)

All of that is incomplete stuff...

**Comment by p-l-** [comment] 2016-12-21 22:13
"Closed" by #399.

**Closed by p-l-** 2016-12-21 22:13 UTC
Labels: contributions wanted, question
