### ISSUE TITLE
I am facing #1615 issue again on Ubuntu 18.04.

### ISSUE THREAD

**Issue by this-is-r-gaurav** [secdev/scapy#1868] opened 2019-02-24 02:29 UTC
**Environment**

    Scapy version: 2.4.2.dev170
    Python version: 3.6.7
    Operating System: Ubuntu 18.04.2
**How to reproduce**
    You can produce this issue by the following script
```python
   #ip_address is any ip address of your choice 
    arp_packet = scapy.ARP(pdst=ip_address)
    ether_packet = scapy.Ether(dst="ff:ff:ff:ff:ff:ff")
    arp_request_broadcast = ether_packet / arp_packet
    answered_list = scapy.srp(arp_request_broadcast,timeout=1,verbose=False)[0]
    print(answered_list)
```

**Actual result**

```
/Code/venv/bin/python3.6 /Code/src/ARP_TESTING.py
Traceback (most recent call last):
  File "/Code/src/ARP_TESTING.py", line 10, in <module>
    send_request(ip_address)
  File "/Code/src/ARP_TESTING.py", line 7, in send_request
    answered_list=scapy.srp(arp_request_broadcast,timeout=1,verbose=False)[0]
  File "/Code/venv/lib/python3.6/site-packages/scapy/sendrecv.py", line 531, in srp
    s = conf.L2socket(promisc=promisc, iface=iface, filter=filter, nofilter=nofilter, type=type)  # noqa: E501
  File "/Code/venv/lib/python3.6/site-packages/scapy/arch/linux.py", line 445, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
  File "/usr/lib/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 1] Operation not permitted
Exception ignored in: <bound method SuperSocket.__del__ of <scapy.arch.linux.L2Socket object at 0x7fcf43ab3320>>
Traceback (most recent call last):
  File "/Code/venv/lib/python3.6/site-packages/scapy/supersocket.py", line 127, in __del__
    self.close()
  File "/Code/venv/lib/python3.6/site-packages/scapy/arch/linux.py", line 481, in close
    set_promisc(self.ins, self.iface, 0)
AttributeError: 'L2Socket' object has no attribute 'ins'
```
The output of `scapy.conf.L2Socket`

```
>>> scap.conf.L2Socket
<L2Socket: read/write packets at layer 2 using Linux PF_PACKET sockets>
```

**Expected result**
```
# A List of packet
```

**Comment by gpotter2** [comment] 2019-02-24 10:11
Hi ! Could you please fill out the issue template ? 

It’s way easier for us to help you if we know what versions / OS you are using :-) in your case, please also provide the output of `scapy.conf.L2Socket`

**Comment by this-is-r-gaurav** [comment] 2019-02-24 10:20
```
OS: Ubuntu 18.04.2 LTS
>>> scap.conf.L2Socker
L2Socket: read/write packets at layer 2 using Linux PF_PACKET sockets>
```

Is this the output you want me to interpret. If anything else required please let me know.

**Comment by gpotter2** [comment] 2019-02-24 10:23
Please fill up the issue template. It is the default content of an issue when you create it. You can also find it over https://github.com/secdev/scapy/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by guedou** [comment] 2019-02-24 10:30
This issue must be closed and #1615 reopened.

We were not able to reproduce the issue. Please provide and example that could help us reproduce and fix it.

**Comment by this-is-r-gaurav** [comment] 2019-02-24 11:01
@gpotter2 I have edited the Issue, Please have a look at it. If i need to update something more i will be doing that

**Comment by gpotter2** [comment] 2019-02-24 11:03
Thanks to your log, you can see that the real issue is:

`PermissionError: [Errno 1] Operation not permitted` = you need to start Scapy/Python as root

It is then followed by a failure in `__del__`, as it couldn’t open the socket in the first place

**Comment by this-is-r-gaurav** [comment] 2019-02-24 11:08
But I am doing that in virtual environment, I have no use case with the root packages.

**Comment by this-is-r-gaurav** [comment] 2019-02-24 11:15
The scapy as well as Python is installed in virtual environment.

**Comment by gpotter2** [comment] 2019-02-24 11:29
The real matter is that it’s not possible to start a raw socket without being root. It doesn’t matter how you installed Scapy, that’s a Linux restriction.

**Comment by this-is-r-gaurav** [comment] 2019-02-24 11:41
I agree with you, so far what i had researched, So i always need to elevate the permission first. Till now no solution for that. Thank you for your time.

**Comment by this-is-r-gaurav** [comment] 2019-02-24 11:45
Can You please have a look at the last comment  below the accepted answer of this question, Can it help in purposing the solution: https://stackoverflow.com/questions/9772068/raw-socket-access-as-normal-user-on-linux-2-4

**Comment by gpotter2** [comment] 2019-02-24 12:10
Sorry, but this isn’t an issue, from scapy’s side.

I’ll be closing this for now, feel free to ask your question on stackoverflow if it’s about bypassing the root requirements

**Closed by gpotter2** 2019-02-24 12:10 UTC

**Comment by this-is-r-gaurav** [comment] 2019-02-24 13:44
Okay thank you
