### ISSUE TITLE
Back to back packet

### ISSUE THREAD

**Issue by valour01** [secdev/scapy#913] opened 2017-10-25 04:01 UTC
I am using scapy to do some network experiments. I have a list of packets. And I try to use the following for loop to send out all the packets.

    for  pkt in pkts:
        send(pkt)

However, I noticed the depart time interval between every packet is about 40ms. I think this interval is too large since I want to create a packet train and all the packets are sent out back to back. Do you have any ideas? Many Thanks

**Comment by gpotter2** [comment] 2017-10-25 13:13
```
>>> a = sniff(count=100)
...:i = time.time()
...:for j in a:
...:    send(j)
...:print(time.time()-i)

Sent 1 packets.
.
Sent 1 packets.
.
[another 98 ones]
0.35880041122436523
```
So to me, it took 0.35 sec to send 100 packets :/
Have you tried using the latest scapy dev version ?
https://github.com/secdev/scapy/archive/master.zip

**Comment by gpotter2** [comment] 2017-10-25 14:24
Hmm,
i cannot reproduce your bug.
We'll need more informations:
- Could you retry using the latest dev version https://github.com/secdev/scapy/archive/master.zip
- What OS are you using ?
- What is your python version ?

**Comment by valour01** [comment] 2017-11-05 15:26
Sorry for the late reply
I am using the python 2.7.6;
I am using the scapy 2.3.3
I am using ubuntu 14.04 x86_64 with kernel 3.13.0-32-generic
It seems that using `send(pkts)` instead of the for loop may narrow down the time interval but still I want to know how small the time interval should be if all the packets are back to back.

I will also try the latest dev version and get back to you later.

**Comment by speakinghedge** [comment] 2017-11-22 20:57
> It seems that using send(pkts) instead of the for loop may narrow down the time interval 

send() creates a new raw socket on each call - and this takes a lot of time:
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1000   40.308    0.040   80.013    0.080 sendrecv.py:264(send)
```
the 40ms IFG are more or less caused by opening a socket, setting socket options, bind ... and so on. sending the data takes more or less nothing (compared to the other activities).

> but still I want to know how small the time interval should be if all the packets are back to back.

calling send() with a list of frames avoids that overhead of the socket setup - I was able to send a frame every 900us.
you could also create a socket and just call its send method on each single frame.

In any case: I bet scapy was not made to be used as a high performance traffic generator.

Depending on your requirements you could use several other options:
- Set the timestamps on your frames as needed and write them to a pcap. use tcpreplay (without any options it will replay the pcap at the speed defined by the timestamps of the frames)
- if stock tcpreplay is to slow: build tcpreplay using pf_ring-zero or netmap
- if this is not an option: check the DPDK - iirc they even have an example on how to replay pcap

Saturating a 1G link should be easy with netmap or DPDK. If you need to create streams with a 10s-of-ns-precise IFG (missing your definition of back to back) some hardware support is required. In this case
- sell your home and buy an IXIA
- no home: try to get an used Endace DAG card 

You should also check ostinato.

**Comment by guedou** [comment] 2017-11-29 09:39
I am closing this issue as answers were provided.

**Closed by guedou** 2017-11-29 09:39 UTC
