### ISSUE TITLE
Issue with ARP function when using CIDR notation

### ISSUE THREAD

**Issue by RochieOreo** [secdev/scapy#3004] opened 2020-12-09 15:11 UTC
#### Brief description

When using the ARP function on a CIDR notation IP address, function doesn't return expected paramiters shown in Scapy documentation.

#### Environment

-   Scapy version: `scapy-2.4.4.dev214` and `scapy-2.4.4`
-   Python version: `Python 3.8.4 `
-   Operating System: `Kali 2020.3`

#### How to reproduce

> test = scapy.all.Ether(dst="ff:ff:ff:ff:ff:ff")/scapy.all.ARP(pdst="192.168.1.0/24")
> 
> test.show()

#### Actual result

> Traceback (most recent call last):
>   File "scan.py", line 8, in <module>
>     test.show()
>   File "/usr/lib/python3/dist-packages/scapy/packet.py", line 1261, in show
>     return self._show_or_dump(dump, indent, lvl, label_lvl)
>   File "/usr/lib/python3/dist-packages/scapy/packet.py", line 1235, in _show_or_dump
>     reprval = f.i2repr(self, fvalue)
>   File "/usr/lib/python3/dist-packages/scapy/fields.py", line 502, in i2repr
>     x = self.i2h(pkt, x)
>   File "/usr/lib/python3/dist-packages/scapy/layers/l2.py", line 136, in i2h
>     iff = self.getif(pkt)
>   File "/usr/lib/python3/dist-packages/scapy/layers/l2.py", line 132, in <lambda>
>     self.getif = (lambda pkt: pkt.route()[0]) if getif is None else getif
>   File "/usr/lib/python3/dist-packages/scapy/packet.py", line 1185, in route
>     return self.payload.route()
>   File "/usr/lib/python3/dist-packages/scapy/layers/l2.py", line 400, in route
>     fld, dst = fld._find_fld_pkt_val(self, dst)
>   File "/usr/lib/python3/dist-packages/scapy/fields.py", line 313, in _find_fld_pkt_val
>     if val == dflts_pkt[self.name] and self.name not in pkt.fields:
>   File "/usr/lib/python3/dist-packages/scapy/base_classes.py", line 133, in __eq__
>     p2, nm2 = self._parse_net(other)
>   File "/usr/lib/python3/dist-packages/scapy/base_classes.py", line 99, in _parse_net
>     tmp = net.split('/') + ["32"]
> AttributeError: 'NoneType' object has no attribute 'split'

#### Expected result

> ###[ Ethernet ]### 
>   dst       = ff:ff:ff:ff:ff:ff
>   src       = 08:00:27:50:1a:ae
>   type      = ARP
> ###[ ARP ]### 
>      hwtype    = 0x1
>      ptype     = IPv4
>      hwlen     = None
>      plen      = None
>      op        = who-has
>      hwsrc     = 08:00:27:50:1a:ae
>      psrc      = Net('192.168.44.4/24')
>      hwdst     = 00:00:00:00:00:00
>      pdst      = 192.168.1.0

#### Related resources

![image](https://user-images.githubusercontent.com/27860421/101651406-f18a1180-3a34-11eb-89ac-cf175afc4125.png)

**Comment by gpotter2** [comment] 2020-12-14 01:32
I can't reproduce this. Make sure you're using the latest version

![B77C7D83-739F-4A62-9A7A-D191E00C50C1](https://user-images.githubusercontent.com/10530980/102030860-8d5caa00-3db4-11eb-991e-d1dce3a57b85.jpeg)

**Comment by ANIKET502** [comment] 2020-12-20 14:56
Hi i am the first one who came to solve this issue please assign this to me for that can resolve this one

**Comment by guedou** [comment] 2020-12-23 16:11
It does work as expected. I am closing this issue as we did not get an answer.

**Closed by guedou** 2020-12-23 16:11 UTC
Labels: needs additional info
