### ISSUE TITLE
Unsolved issues in compatibility.py in latest version

### ISSUE THREAD

**Issue by yuval9313** [secdev/scapy#1218] opened 2018-03-07 17:01 UTC
I get stuck on multiple types of problems caused by compatibility.py in Scapy 2.3.3
**I've read some guides on some fixes but other issues keep occurring**
I've installed the older version (scapy 2.3.2) which has its own unfixable problems
please help me.

I already tried `pip install --pre scapy`
and the answer is: `Requirement already satisfied: scapy`

**I tried a lot of methods in order to fix it None of them worked**

and yet problems still occurring

p,s running time is very low, it takes about 2 -3 min for Scapy to load also in CMD

**Comment by guedou** [comment] 2018-03-07 17:07
Duplicate of #1217. There is no way we can help you if you don't report your OS, Python an Scapy versions ....

Please stop opening issues. This is harassment!

**Closed by guedou** 2018-03-07 17:07 UTC

**Comment by yuval9313** [comment] 2018-03-07 17:10
os: windows 10 pro version 1709 X64
python 2.7.6.1
scapy currently installed with: `pip install --pre scapy`

**Comment by yuval9313** [comment] 2018-03-07 17:18
sorry about the dup I new in the GitHub community
I saw the comment in the #1217 and i have tried it
again `Requirement already satisfied: scapy`
I used it again with `pip install --upgrade --pre --ignore-installed scapy`

and now i have other issue with wireshark might be because it is not updated
thank you for your help

**Comment by yuval9313** [comment] 2018-03-07 17:55
I found new issues
```
WARNING: PyX dependencies are not installed ! Please install TexLive or MikTeX.
WARNING: No route found for IPv6 destination :: (no default route?)
WARNING: traitlets not available. Some Scapy shell features won't be available.
ERROR: Invalid alias: The name ls can't be aliased because it is a keyword or builtin.
ERROR: Invalid alias: The name copy can't be aliased because it is a keyword or builtin.
```
should i be concerned about any of them?

**Comment by gpotter2** [comment] 2018-03-07 18:40
Please install ipython
`pip install ipython`
Should fix the "error" messages (which are not important)

Those warnings are common

**Comment by yuval9313** [comment] 2018-03-07 20:31
Thank you for your help

**Comment by gpotter2** [comment] 2018-03-07 21:44
No

**Comment by yuval9313** [comment] 2018-03-08 14:39
I dont want to open another ticket but I'm facing an issue where powershell.exe opens anytime I open scapy in pycharm

Thank you in advence
