### ISSUE TITLE
sniff() dies when EOF on offline kwarg

### ISSUE THREAD

**Issue by stryngs** [secdev/scapy#2764] opened 2020-08-15 05:44 UTC
Hi there.  I found out by running sniff(offline='<blah>') that sniff() will die out when the end of the file is reached.  I am now using scapy to parse ubertooth packets.  The way I leverage it, I stream the raw ubertooth to a file and then read that in via sniff w/ offline.

If the bluetooth traffic is slower than the rate scapy can consume, it hits the EOF.  Once EOF sniff() dies.  A while true loop is my current idea for a workaround but am really wondering if there is a way to add in a parameter to keep sniff() open and tail -f so to speak.  I don't even know if this is possible and failed in my attempts.

Curious your thoughts.  Thanks!

**Comment by gpotter2** [comment] 2020-08-15 11:49
This is mostly by design. Checking for EOF really is the cleanest way of ending our stream.
What you could do is to extend `PcapReader` to make it not throw an EOFError then inject it into sniff.
Something like (untested):

```python
class Reader(PcapReader):
    def read_packet(self, size=MTU):
        try:
            return super(Reader, self).read_packet(size)
        except EOFError:
            return none

sniff(opened_socket=Reader("some_pcap.pcap"))
```

**Comment by gpotter2** [comment] 2020-08-16 23:40
We usually do not answer questions here but I thought this was interesting. Closing

**Closed by gpotter2** 2020-08-16 23:40 UTC
Labels: discussion

**Comment by stryngs** [comment] 2021-05-21 07:18
Just saw your response @gpotter2 -- Curious to see how that works.  Thank you for the input!!

**Comment by stryngs** [comment] 2021-09-09 03:02
@gpotter2 It worked exactly as you thought it would.  I tuned the Ubertooth to sniff only for a certain MAC, made the MAC silent and scapy stayed silent via prn.  Made the MAC speak and prn sung a song.

Very nice work and thank you for responding to this.  I look forward to merging this into my code.  100% realtime Bluetooth sniffing with scapy via an ubertooth!
