### ISSUE TITLE
ARP packets are always sent to conf.iface instead of interface specified by route table

### ISSUE THREAD

**Issue by dnvanderwerff** [secdev/scapy#1891] opened 2019-03-07 16:14 UTC
#### Brief description

ARP packets are always sent to conf.iface instead of the interface determined by the route table (bug introduced in commit 435918e3d8e9). 

#### Environment

-   Scapy version: 2.4.2 (commit 435918e3d8e95b7374fadd8c6d962ee9b5032fcb)
-   Python version: 3.6.7
-   Operating System: Ubuntu 18.04

#### How to reproduce

Executing the following example shows that the ARP packet is sent to conf.iface instead of using the route table to determine which interface to use:

```
#!/usr/bin/env python
from scapy.all import *

conf.iface = "foobar"

conf.route.add(net="99.99.99.0/24", dev="eth0")

x = Ether(dst=ETHER_BROADCAST)/ARP(op="who-has", pdst="99.99.99.1")

# Should use "eth0", but uses "foobar"
x.show2()
```

#### Actual result
The ARP packet is sent to interface "foobar" (attempted).

#### Expected result
The ARP packet should be sent to "eth0", as prescribed by the entry added to the route table.

#### Explanation of the bug
The interface to which a packet is sent, is computed with 'getif', based on the payload (line 116 in scapy/layers/l2.py, before commit 435918e3d8e95b7374fadd8c6d962ee9b5032fcb): 
```
112 class SourceMACField(MACField):
113     __slots__ = ["getif"]
114     def __init__(self, name, getif=None):
115         MACField.__init__(self, name, None)
116         self.getif = ((lambda pkt: pkt.payload.route()[0])
117                        if getif is None else getif)
```
In case of ARP packets (that do not have a payload), 'getif' used to be modified as follows (line 139 in scapy/layers/l2.py, before commit 435918e3d8e95b7374fadd8c6d962ee9b5032fcb):
```
135 class ARPSourceMACField(SourceMACField):
136     def __init__(self, name):
137         super(ARPSourceMACField, self).__init__(
138            name,
139            getif=lambda pkt: pkt.route()[0],
140        )
```
However, since commit 435918e3d8e95b7374fadd8c6d962ee9b5032fcb, line 139 has been removed, meaning that 'getif' still equals pkt.payload.route() for ARP packets. As they do not have a payload this function returns None. As a result, the default interface conf.iface is chosen, which might not be the interface that the packet needs to go to. If it is not, both the interface and source MAC address of the ARP packet will be incorrect. If it is, the error is not observed (indicating why this bug is not always visible).

**Comment by gpotter2** [comment] 2019-03-25 21:59
Duplicate of https://github.com/secdev/scapy/issues/1518#issuecomment-476376467

**Closed by gpotter2** 2019-03-25 21:59 UTC
Labels: bug
