### ISSUE TITLE
Scapy 2.4.2 uses too much memory when sending packets

### ISSUE THREAD

**Issue by aligh993** [secdev/scapy#1897] opened 2019-03-11 14:52 UTC
#### Brief description

Scapy 2.4.2 uses too much memory (or misuses memory!) when sending  packets. It can easily be verified when you are sending packets in sequence inside a loop. In my testing, sending 1000 packet in Scapy consumes about 1GB of memory.  The problem persists in Scapy 2.4.1 and 2.4.2, but Scapy 2.4.0 works fine.

#### Environment

-   Scapy version: 2.4.2
-   Python version: 3.7.0
-   Operating System: Windows 10

#### How to reproduce

>you can test it by:

```
from scapy.all import *

for i in range(1000):
	sr1(IP(dst="172.17.41.146")/TCP(), timeout=0.01, verbose=0)
```
*(code edited by gpotter2, to reproduce the issue more accurately)*

**Comment by p-l-** [comment] 2019-03-12 08:21
Hi,

Interesting. Do you have similar issues with `sr([IP(dst="172.17.41.146")/TCP()] * 1000, inter=.01, timeout=.01)`?

**Comment by p-l-** [comment] 2019-03-12 08:29
Also, what is the result of `conf.route.route('172.17.41.146')`? I cannot reproduce that under Linux, so that might be a Windows-specific issue.

**Comment by guedou** [comment] 2019-03-12 09:47
There is a slight difference with the following script:
```
from scapy.all import *
from memory_profiler import profile

@profile
def test():
    store = list()
    for i in range(1000):
        store.append(raw(IP(dst="172.17.41.146")/TCP()))

test()
```

Python2.7
master: ~64MB  
v2.4.0:  ~60MB

Python3.6:
master: ~44MB  
v2.4.0:  ~41MB

The results are similar on Linux while sending packets with `sr1()`.

**Comment by aligh993** [comment] 2019-03-12 13:56
> Hi,
> 
> Interesting. Do you have similar issues with `sr([IP(dst="172.17.41.146")/TCP()] * 1000, inter=.01, timeout=.01)`?

**Comment by aligh993** [comment] 2019-03-13 12:32
> Hi,
> 
> Interesting. Do you have similar issues with `sr([IP(dst="172.17.41.146")/TCP()] * 1000, inter=.01, timeout=.01)`?

No. It works fine with Scapy 2.4.2

The memory leak bug is only presents when I am sending packets inside a loop.

**Comment by p-l-** [comment] 2019-03-13 14:12
Calling @gpotter2 to the rescue. Any idea what has changed in Windows-specific code that could lead to such a memory leak?

**Comment by aligh993** [comment] 2019-03-13 14:21
> There is a slight difference with the following script:
> 
> ```
> from scapy.all import *
> from memory_profiler import profile
> 
> @profile
> def test():
>     store = list()
>     for i in range(1000):
>         store.append(raw(IP(dst="172.17.41.146")/TCP()))
> 
> test()
> ```
> Python2.7
> master: ~64MB
> v2.4.0: ~60MB
> 
> Python3.6:
> master: ~44MB
> v2.4.0: ~41MB
> 
> The results are similar on Linux while sending packets with `sr1()`.

It doesn't show up in python memory profiler. But you can verify it through Windows Task Manager.

**Comment by gpotter2** [comment] 2019-03-13 16:29
Could you retry using 2.4.3rc ?

That’s weird :/ either I deleted a Npcap/Winpcap cleanup call (which I doubt, never seen such a thing), either one of the caches is buggy.. I’ll try to investigate when I have the tile

**Comment by gpotter2** [comment] 2019-03-17 18:03
I'm able to reproduce.

**Comment by gpotter2** [comment] 2019-03-24 15:12
@aligh993 Hi ! This should be fixed in https://github.com/secdev/scapy/pull/1847

**Closed** 2019-03-24 18:40 UTC
Labels: bug
