### ISSUE TITLE
Support for adapters without IP address (like Napatech)

### ISSUE THREAD

**Issue by robgom** [secdev/scapy#1719] opened 2018-11-30 11:18 UTC
#### Brief description

I have a Napatech card. It comes with custom wpcap.dll and it's visible in Wireshark (and winpcapy IIRC). But its interfaces are not visible in Windows - they don't have IP, routing, nothing.

When I import scapy and print the interfaces, the list is empty.

Hence my question - is it possible to utilize such adapters through scapy for sniffing only?

Regards,
Robert

#### Environment

-   Scapy version: 2.4.0
-   Python version: 2.7
-   Operating System: Windows 10 64 bit

#### How to reproduce

> install Napatech card, try to sniff packets with it

While this looks like a question, I think my initial experiments shown that scapy.IFACES was empty and I couldn't perform sniffing with them - scapy.sniff(iface='napa0') resulted in "ValueError: Unknown network interface 'napa0'".

Regards,
Robert

**Comment by gpotter2** [comment] 2018-11-30 11:57
Hi !

Could you report the output of both
`get_windows_if_list()`
and
`get_if_list()`

You may consider obfuscating it if needed. It will give the key infos to understand what’s happening here

**Comment by robgom** [comment] 2018-11-30 12:48
Thank you for the feedback.

```
>>> scapy.get_if_list()
['napa0', 'napa1', 'napa2', 'napa3', '\\Device\\NPF_{......}', '\\Device\\NPF_{......}']
>>> scapy.get_windows_if_list()
# only those 2 NPF interfaces: description empty, guid as after NPF above, mac, name, netid, win_index
>>> scapy.IFACES
# only those 2 NPF interfaces

Hope that helps.

Robert

**Comment by robgom** [comment] 2018-11-30 12:50
There are no warnings during scapy loading.
Custom wpcap.dll overwrites official one - it's ABI compatible. winpcapy can see the interfaces (and give them to scapy, as seen in my previous comment.

Robert

**Comment by robgom** [comment] 2018-12-03 07:58
Thank you for the tip.
I'm afraid it won't help.
The first reason is that mentioned code change addresses PowerShell cmdlet
not available in Windows 7 (no Get-NetAdapter).
And the second - the interfaces aren't actually hidden, I believe. Under
Device Manager, they are not it "Network Adapters" group, but rather in
"Napatech Software Suite Class".
So far the only entry points to access the cards are:
- custom Napatech tools (executables)
- their dlls (wpcap)

I think it could be doable in scapy by querying pcap first, then populate
adapters properties only when found by other means. That way Napatech cards
would have most properties uninitialized (None?) indicating that they are
not suitable for operations other than sniffing. However, I also think it'd
be a significant refactoring. (Please take that with a grain of salt, as I
haven't analyzed the code thoroghly)

Robert

**Comment by gpotter2** [comment] 2018-12-03 11:46
Thanks for the feedback, I’ll have a look on that

Please remain consistent in your report, you posted your issue with
![1efeb52b-3f32-412c-aaf0-302a5b74908e](https://user-images.githubusercontent.com/10530980/49371980-75e48400-f6f9-11e8-93e1-3b93a1fc938e.jpeg)
But now report a Windows 7 version

**Comment by robgom** [comment] 2018-12-03 11:51
Apologies for the noise - I've changed machines during my experiments.

So, while the results should be consistent, currently I have access to
Windows 7 only.

Robert

Pon., 3 gru 2018, 12:46: Gabriel Potter <notifications@github.com>
napisał(a):

**Comment by gpotter2** [comment] 2019-01-12 14:59
@robgom Hello ! I have some news, could you try https://github.com/secdev/scapy/pull/1759 out?

It has lots of general windows improvements (like the loading speed), and should theoretically fix this issue

**Comment by guedou** [comment] 2019-01-14 09:56
@robgom thanks for your feedback.

I will close the issue for now. Please reopen it, if anything goes wrong during your tests.

**Comment by p-l-** [comment] 2019-01-30 21:01
**Not** fixed, according to @gpotter2.

**Comment by gpotter2** [comment] 2019-02-03 17:17
@robgom Hi ! Could you retry with https://github.com/secdev/scapy/pull/1833 ? Thanks !

**Comment by robgom** [comment] 2019-02-03 17:39
Will try tomorrow. Do you need any extra debug info if it doesn,t work?

Niedz., 3 lut 2019, 18:17: Gabriel Potter <notifications@github.com>
napisał(a):

**Comment by gpotter2** [comment] 2019-02-03 17:59
Thanks a lot !
The output of:
- `get_if_list()`
- `get_windows_if_list()`
- `[x.__dict__ for x in IFACES.data.values()]`

should allow to debug pretty much anything. You may send it over to me by email at `gabriel[at]potter[dot]fr` to keep it private

**Comment by robgom** [comment] 2019-02-05 07:50
I've done the following:
- git fetch --all
- git checkout 80211win
This is an editable install, so Python should pick the changes
automatically, right?
Because I don't see any difference in behaviour. get_if_list() is empty and
get_windows_if_list() returns list of real interfaces + Microsoft ISATAP
ones. No sign of Napatech interfaces.

Please let me know if I can assist you further.

Robert

**Comment by gpotter2** [comment] 2019-02-05 09:09
I use git push -f a lot, you would also need `git pull` followed by `git reset --hard upstream/80211win`

**Comment by gpotter2** [comment] 2019-02-05 11:43
I don’t get it. Nothing on `get_if_list()` would mean we have nothing returned by winpcap ?!

Could you try
```python
from scapy.modules.winpcapy import *
def test():
            err = create_string_buffer(PCAP_ERRBUF_SIZE)
            devs = POINTER(pcap_if_t)()
            if pcap_findalldevs(byref(devs), err) < 0:
                return
            p = devs
            # Iterate through the different interfaces
            while p:
                name = plain_str(p.contents.name)  # GUID
                description = plain_str(p.contents.description)  # NAME
                print(":".join([name, description]))
                p = p.contents.next
```

**Comment by robgom** [comment] 2019-02-05 12:21
Well,
test() method output looked much more interesting (sorry for the
formatting, there are 8 devices returned - 4 Napatechs, 4 real NICs - quite
matching my setup)
napa0:NT 3G configured device. Stream ....
napa1:NT 3G configured device. Stream ....
napa2:NT 3G configured device. Stream ....
napa3:NT 3G configured device. Stream ....
\Device\NPF_{GUID1}:Intel Gigabit Adapter

\Device\NPF_{GUID2}:Intel Gigabit Adapter
\Device\NPF_{GUID3}:Intel Gigabit Connection
\Device\NPF_{GUID1}:Intel I217-LM

(I had to import plain_str from scapy.compat, if it matters).

Regards,
Robert

**Comment by robgom** [comment] 2019-02-05 12:38
I have added debug messages to arch/pcapdnet.py, line 84, right before "if
conf.use_winpcapy:" line.
And it was printed twice - once with conf.use_winpcapy = True, second time
= False.
I'm guessing some higher level logic fails to pass control to the code in
question.

HTH,
Robert

**Comment by robgom** [comment] 2019-02-05 13:00
Ok, I think I've found something relevant.
The code fails on pcap_create import from winpcapy. And that's npcap
specific, I suppose. We still use winpcap, so there's no such attribute, so
the code can't proceed further.

Regards,
Robert

**Comment by gpotter2** [comment] 2019-02-05 13:34
Here’s the full function we use:
```python
def load_winpcapy():
            """This functions calls Winpcap/Npcap pcap_findalldevs function,
            and extracts and parse all the data scapy will need to use it:
             - the Interface List
            This data is stored in their respective conf.cache_* subfields:
                conf.cache_iflist
            """
            err = create_string_buffer(PCAP_ERRBUF_SIZE)
            devs = POINTER(pcap_if_t)()
            if_list = {}
            if pcap_findalldevs(byref(devs), err) < 0:
                return
            try:
                p = devs
                # Iterate through the different interfaces
                while p:
                    name = plain_str(p.contents.name)  # GUID
                    description = plain_str(p.contents.description)  # NAME
                    flags = p.contents.flags  # FLAGS
                    ips = []
                    a = p.contents.addresses
                    while a:
                        # IPv4 address
                        family = a.contents.addr.contents.sa_family
                        ap = a.contents.addr
                        if family == socket.AF_INET:
                            val = cast(ap, POINTER(sockaddr_in))
                            val = val.contents.sin_addr[:]
                        elif family == socket.AF_INET6:
                            val = cast(ap, POINTER(sockaddr_in6))
                            val = val.contents.sin6_addr[:]
                        else:
                            # Unknown address family
                            # (AF_LINK isn't a thing on Windows)
                            a = a.contents.next
                            continue
                        addr = inet_ntop(family, bytes(bytearray(val)))
                        if addr != "0.0.0.0":
                            ips.append(addr)
                        a = a.contents.next
                    if_list[name] = (description, ips, flags)
                    p = p.contents.next
                conf.cache_iflist = if_list
            except Exception:
                raise
            finally:
                pcap_freealldevs(devs)
```

Could you report the output of `conf.cache_iflist` ? If you have any ideas of why it doesn’t work on your machine feel free to report it.

Thanks a lot for your help on that issue,
Regards

**Comment by gpotter2** [comment] 2019-02-05 13:47
Thanks a lot that’s the issue ! (Sorry for the previous deleted comment, I hadn’t reloaded the page for your answer)

**Comment by gpotter2** [comment] 2019-02-06 16:49
Thanks again for all your help with this issue.

I’ve added the fixes to https://github.com/secdev/scapy/pull/1833, with also a Winpcap unit test so that we don’t get further of those regressions in the future

**Comment by robgom** [comment] 2019-02-06 21:01
Much more promising, if you ask me:

D:\git\scapy>python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32
bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy import all as scapy
>>> scapy.ifaces
INDEX  IFACE
IP            MAC
12     Intel(R) Ethernet Connection I217-LM
1.1.1.1       11:11:11:11:11:11
11     Intel(R) I210 Gigabit Network Connection                   2.2.2.2
22:22:22:22:22:22
13     Intel(R) Gigabit CT Desktop Adapter                        3.3.3.3
33:33:33:33:33:33
15     Intel(R) Gigabit CT Desktop Adapter #3                     4.4.4.4
44:44:44:44:44:44
-4     [Unknown] NT 3G configured device. Stream 252. Transmit 0
None          ff:ff:ff:ff:ff:ff
-3     [Unknown] NT 3G configured device. Stream 1. Transmit 1
None          ff:ff:ff:ff:ff:ff
-2     [Unknown] NT 3G configured device. Stream 2. Transmit 2
None          ff:ff:ff:ff:ff:ff
-1     [Unknown] NT 3G configured device. Stream 3. Transmit 3
None          ff:ff:ff:ff:ff:ff
16     Microsoft ISATAP Adapter                                   None
19     Microsoft ISATAP Adapter #3                                None
17     Microsoft ISATAP Adapter #2                                None
18     Microsoft ISATAP Adapter #4                                None

Those negatives are a bit strange, but the ifaces are there :)

And after that:
>>> scapy.sniff(iface='[Unknown] NT 3G configured device. Stream 252.
Transmit 0', count=1, timeout=1)
Packets captured: ICMP: TCP: .... (this from memory, but some were
captured, I haven't analyzed their contents, though)

However, there's some inconsistency:

>>> scapy.get_if_list()
['napa3', 'napa2', 'napa1', 'napa0', '\\Device\\NPF_{GUID}',
'\\Device\\NPF_{GUID}', '\\Device\\
NPF_{GUID}', '\\Device\\NPF_{GUID}']

And:
>>> scapy.sniff(iface='napa0', count=1, timeout=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scapy\sendrecv.py", line 868, in sniff
    *arg, **karg)] = iface
  File "scapy\arch\pcapdnet.py", line 443, in __init__
    self.ins = open_pcap(iface, MTU, self.promisc, 100, monitor=monitor)  #
noqa: E501
  File "scapy\arch\windows\__init__.py", line 790, in open_pcap
    iface_pcap_name = pcapname(iface)
  File "scapy\arch\windows\__init__.py", line 758, in pcapname
    return IFACES.dev_from_name(dev).pcap_name
  File "scapy\arch\windows\__init__.py", line 685, in dev_from_name
    raise ValueError("Unknown network interface %r" % name)
ValueError: Unknown network interface 'napa0'


Kudos for all the work :)

By the way, while on that - do you think the same could help in case with
windows interfaces without IP?
Most tutorials recommend disabling IP (removing IPv4 in windows for
example) for sniffing and we couldn't do that because of scapy, which then
ignored the ifaces.

Regards,
Robert

**Comment by gpotter2** [comment] 2019-02-06 21:20
<details>
<summary>previous post formatted on markdown</summary>

Much more promising, if you ask me:

```

D:\git\scapy>python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32
bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy import all as scapy
>>> scapy.ifaces
INDEX  IFACE
IP            MAC
12     Intel(R) Ethernet Connection I217-LM
1.1.1.1       11:11:11:11:11:11
11     Intel(R) I210 Gigabit Network Connection                   2.2.2.2
22:22:22:22:22:22
13     Intel(R) Gigabit CT Desktop Adapter                        3.3.3.3
33:33:33:33:33:33
15     Intel(R) Gigabit CT Desktop Adapter #3                     4.4.4.4
44:44:44:44:44:44
-4     [Unknown] NT 3G configured device. Stream 252. Transmit 0
None          ff:ff:ff:ff:ff:ff
-3     [Unknown] NT 3G configured device. Stream 1. Transmit 1
None          ff:ff:ff:ff:ff:ff
-2     [Unknown] NT 3G configured device. Stream 2. Transmit 2
None          ff:ff:ff:ff:ff:ff
-1     [Unknown] NT 3G configured device. Stream 3. Transmit 3
None          ff:ff:ff:ff:ff:ff
16     Microsoft ISATAP Adapter                                   None
19     Microsoft ISATAP Adapter #3                                None
17     Microsoft ISATAP Adapter #2                                None
18     Microsoft ISATAP Adapter #4                                None
```

Those negatives are a bit strange, but the ifaces are there :)

And after that:

```
>>> scapy.sniff(iface='[Unknown] NT 3G configured device. Stream 252.
Transmit 0', count=1, timeout=1)
Packets captured: ICMP: TCP: ....
```

(this from memory, but some were
captured, I haven't analyzed their contents, though)

However, there's some inconsistency:

```
>>> scapy.get_if_list()
['napa3', 'napa2', 'napa1', 'napa0', '\\Device\\NPF_{GUID}',
'\\Device\\NPF_{GUID}', '\\Device\\
NPF_{GUID}', '\\Device\\NPF_{GUID}']
```

And:

```
>>> scapy.sniff(iface='napa0', count=1, timeout=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scapy\sendrecv.py", line 868, in sniff
    *arg, **karg)] = iface
  File "scapy\arch\pcapdnet.py", line 443, in __init__
    self.ins = open_pcap(iface, MTU, self.promisc, 100, monitor=monitor)  #
noqa: E501
  File "scapy\arch\windows\__init__.py", line 790, in open_pcap
    iface_pcap_name = pcapname(iface)
  File "scapy\arch\windows\__init__.py", line 758, in pcapname
    return IFACES.dev_from_name(dev).pcap_name
  File "scapy\arch\windows\__init__.py", line 685, in dev_from_name
    raise ValueError("Unknown network interface %r" % name)
ValueError: Unknown network interface 'napa0'
```

Kudos for all the work :)

By the way, while on that - do you think the same could help in case with
windows interfaces without IP?
Most tutorials recommend disabling IP (removing IPv4 in windows for
example) for sniffing and we couldn't do that because of scapy, which then
ignored the ifaces.

Regards,
Robert

</summary>

To explain:
- interfaces that have negative indexes are the ones that are not described in Windows, but only on Winpcap
- the inconsistencies are also linked to Winpcap: it returns the interfaces “as-is”, expecting some to be with `\\Device...` and some without
- You are right, it would be a good idea to support direct pcap_name usage when sniffing. On other interfaces, it would be like passing `\\Device\\...`, but that still counts as an improvement

Note: I tried to format your previous post on github, but then realized github locks formatting (even after editing) when the message comes from an email. Sorry for the noise

**Comment by robgom** [comment] 2019-02-08 07:52
I had a chance to (partially) verify the other part of the question. If
that's not relevant, please let me know, I can open another thread.
The other part was: what if I disable IPv4 for sniffing-only adapters (to
avoid any accidental packets sending)?
It can be done in Windows by unchecking IPv4 layer on adapter properties.

So, before removing IPv4:

>>> scapy.ifaces
INDEX  IFACE
IP            MAC
11     Intel(R) I210 Gigabit Network Connection
172.16.20.1   RE:AL:MA:CA:DD:RR

And after removing:
>>> scapy.ifaces
INDEX  IFACE
IP            MAC
-5     [Unknown] Intel(R) I210 Gigabit Network Connection
172.16.20.1   ff:ff:ff:ff:ff:ff

- index became negative - that's ok, I suppose
- [Unknown] prepended to iface name
- previous IP retained
- MAC address changed to ff:ff:ff:ff:ff:ff

From what I see, that should work for us and IP/MAC things are just
irrelevant in sniffing context.
The only remaining aspect would be to verify actual sniffing with such
configuration.

Regards,
Robert

**Comment by gpotter2** [comment] 2019-02-08 09:40
The Mac is set arbitrarily. As it’s not provided we just set a random one.

**Closed** 2019-02-08 10:27 UTC
Labels: enhancement
