### ISSUE TITLE
AsyncSniffer exception seen when iface is a list

### ISSUE THREAD

**Issue by ssundari** [secdev/scapy#3907] opened 2023-02-18 17:11 UTC
Scapy 2.4.5 and Python 3.8.2

t = AsyncSniffer(iface="enp0s3", count=200) => works
t = AsyncSniffer(iface=["enp0s3","enp0s2"], count=200)  => getting below exception.

  File "python3.8/site-packages/scapy/arch/common.py", line 65, in get_if
    return ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
AttributeError: 'list' object has no attribute 'encode'

**Comment by evverx** [comment] 2023-02-18 23:01
It appears to be a duplicate of https://github.com/secdev/scapy/issues/3191 and was already fixed in 430f8942fe086553fcd6ad1444e886a343bfd658.

**Comment by KhazAkar** [comment] 2023-02-20 15:01
@ssundari according to comment above, I'd suggest first trying the newest available scapy version, which is **2.5.0**

**Closed** 2023-02-20 19:31 UTC
