### ISSUE TITLE
Import missing & mixup of psm status/result values in bluetooth.py

### ISSUE THREAD

**Issue by susengold** [secdev/scapy#189] opened 2016-06-07 13:40 UTC
Hi,

in scapy version 2.3.2 seems that there is an import missing in bluetooth.py which results in an error message like:
>> : global name 'sndrcv' is not defined.

Additionally the result and status values for psm connection response are mixed up.
Both can be fixed with the attached patch.

If agreed, could the patch please be integrated into next release?

Thanks a lot
Susen

[bluetooth.zip](https://github.com/secdev/scapy/files/302717/bluetooth.zip)

**Comment by guedou** [comment] 2016-06-07 14:57
Could you confirm that the issue is sill present on the GitHub version ?

Also, it is more convenient to submit your patch as a pull-request than attaching it to an issue.

**Comment by susengold** [comment] 2016-06-09 16:24
Hi, 

i already checked under github repository that the issue is still present.
scapy/scapy/layers/bluetooth.py

I can create a pull-request...

Susen

**Comment by p-l-** [comment] 2016-06-10 19:59
Creating a PR is easier for us plus it credits the author of the code!

**Comment by guedou** [comment] 2016-08-24 12:46
Fixed in PR #198

**Closed by guedou** 2016-08-24 12:46 UTC
