### ISSUE TITLE
Dead loop in sniff

### ISSUE THREAD

**Issue by drgnkpr** [secdev/scapy#520] opened 2017-02-21 20:21 UTC
The function sniff in sendrecv.py has a potential dead loop. When using offline mode with lfilter but timeout is not given, if lfilter can't find a packet in pcap file, lines 603 to 628 in sendrecv.py is in a dead loop.

**Comment by guedou** [comment] 2017-02-21 20:25
Could you provide an example and details (OS, Scapy version, ...) that could help us reproduce your issue ?

**Comment by drgnkpr** [comment] 2017-02-21 21:43
The code is run on Ubuntu 16.04 with Python 2.7.12. Scapy version is 2.3.3. I can't post my pcap file here but it contains only ARP packets and I want to filter out TCP packets using:

pkts = sniff(offline=tracefile, lfilter=isprotocol('TCP'))

**Comment by p-l-** [comment] 2017-02-22 07:04
Could you provide at least the code of `isprotocol()`? I cannot reproduce your issue.

**Comment by drgnkpr** [comment] 2017-02-22 18:48
Here is the code:

def isprotocol(proto):
    """
    Validate the packet for particular IP Protocol.

    :param proto: - protocol to be filtered
    :type proto: - scapy.base_classes.Packet_metaclass

    :returns: packet that has matched protocol
    """
    return lambda pkt: pkt.haslayer(proto)

**Comment by p-l-** [comment] 2017-02-22 19:18
First (but that's not important), we prefer `proto in pkt` rather than `pkt.haslayer(proto)`.

Your code is weird You may want to check if the following code works?
```Python
pkts = sniff(offline=tracefile, lfilter=lambda pkt: TCP in pkt)
```

**Comment by drgnkpr** [comment] 2017-02-22 20:24
The code you provide still has the same issue.

How can I use the development code?

**Comment by drgnkpr** [comment] 2017-02-22 20:31
Okay, I confirm that the issue is resolved in the development code.

**Comment by gpotter2** [comment] 2017-02-25 19:32
So let's close this ?

**Closed** 2017-02-25 22:32 UTC
