### ISSUE TITLE
sendp() sends 802.3 twice

### ISSUE THREAD

**Issue by gdsel** [secdev/scapy#724] opened 2017-07-17 19:26 UTC
If I construct an 802.3 frame as follows:
`dot3_frame=Dot3(dst='01:80:c2:00:00:01', src='ff:ff:ff:ff:ff:ff', len=3)/LLC(dsap=0, ssap=1, ctrl=2)/Padding('\x00'*43)`

And then I send the previously created frame:
`sendp(dot3_frame, iface=IFACES.dev_from_index(6))`

In Wireshark I see scapy is sending the frame twice (see [802_3_scapy_sent_twice.zip](https://github.com/secdev/scapy/files/1153737/802_3_scapy_sent_twice.zip)).

I am running Windows 10 with Python 2.7.2 and Scapy 2.3.3.dev519.

**Comment by p-l-** [comment] 2017-07-18 13:36
Do you have the same issue with other packet types?

**Comment by stryngs** [comment] 2017-08-09 02:01
I have the same issues when sending 802.11 via sendp()

Would love to get to the bottom of it.  What is unique, when capturing, I get:
RadioTap / Dot11 / Dot11QoS / LLC / SNAP / IP / TCP 192.168.30.119:53411 > 192.168.30.100:8000 R / Padding
RadioTap / Dot11 / Dot11QoS / LLC / SNAP / IP / TCP 192.168.30.119:53411 > 192.168.30.100:8000 R

The first packet received has Padding(), and the 2nd one does not.  The 1st received is a binary match of the sendp() object.

**Comment by stryngs** [comment] 2017-08-09 04:13
After carefully setting up a test environment tonight, I can attest to the following:

    - Scapy has some weird issues when it comes to sendp() while sniff() on the same NIC
    - This might be avoided by creating virtual interfaces.  More to follow on this later
    - Without getting to deep into it tonight, here is the tl;dr
        - sendp() while sniff() will result in a double print of output via prn()
        - Testing reveals that only 1 frame is sent even though sniff() shows 2
        - Will have to debug into the code to figure out how to prevent the double prints as using prn or lfilter for a counting mechanism where X is the object, results in having to account for 2 Xs == 1X on prn() or anything to where you are capturing an X object
    - Will address this with an indepth POC tomorrow
        - This is an issue and should be rectified, but having tested what I did, it proves scapy by itself isn't sending twice, just that prn() or lfilter() when using them as closures and getting counts, is currently broken for the same NIC per se.

**Comment by stryngs** [comment] 2017-08-10 04:21
Okay, ran out of time tonight.  No further promises on when this writeup is coming, only that it will be done.  Sorry for the mislead.

**Comment by stryngs** [comment] 2017-08-10 04:35
@gdsel Are you wiresharking with the same NIC you are sendp() with?

**Comment by p-l-** [comment] 2017-08-10 12:13
@stryngs I suppose in your specific case that the packet is seen when you send it, and, since you are in monitor mode it is also received. The sent packet has no `Padding` layer, which is added by the driver, and the received packet has it.

**Comment by p-l-** [comment] 2017-08-10 12:17
@gdsel can you run a similar capture with the following packet (without the payload)

```Python
dot3_frame=Dot3(dst='01:80:c2:00:00:01', src='ff:ff:ff:ff:ff:ff', len=3)/LLC(dsap=0, ssap=1, ctrl=2)
```

**Comment by gdsel** [comment] 2017-08-10 18:19
@stryngs  - Yes, I am running a Wireshark capture on the same NIC that I am calling sendp() on.

@p-l- I ran the following command and I see the frame appear twice in Wireshark (see attachment). In the attached capture I am running Wireshark on the same interface that I am transmitting on.
[scapy_dot3_send_twice.zip](https://github.com/secdev/scapy/files/1215577/scapy_dot3_send_twice.zip)


`sendp(Dot3(dst='01:80:c2:00:00:01', src='ff:ff:ff:ff:ff:ff', len=3)/LLC(dsap=0, ssap=1, ctrl=2), iface="Intel(R) PRO/1000 GT Desktop Adapter")`

**Comment by p-l-** [comment] 2017-08-10 18:49
I cannot reproduce your issue under Linux. @gpotter2 could you try to reproduce that under Windows?

**Comment by gpotter2** [comment] 2017-08-11 10:21
WIll do.
Although I don't currently have my window machine with me, so it might take a week...

**Comment by stryngs** [comment] 2017-08-17 03:06
Just an update.  I have not forgot about this.  This issue is something I definitely would like to either fix or figure out the suggested workaround.  Things are busy in my personal life right now, so I just haven't had the time to play catchup.  I'm hoping to make some time available next week.

@p-l- Is there something I can do, PCAP wise, etc, to help out?

**Comment by gpotter2** [comment] 2017-08-17 05:57
@stryngs 
`Testing reveals that only 1 frame is sent even though sniff() shows 2` 
Are you sure of this ?
 That's not what @gdsel has
https://github.com/secdev/scapy/issues/724#issuecomment-321632920

**Comment by gdsel** [comment] 2017-08-17 16:44
@gpotter2 I see two copies in Wireshark for non-Dot3 frames as well. For example I also see two copies when I send this:
{quote}
sendp(Ether(dst='ff:ff:ff:ff:ff:ff')/IP(dst="127.0.0.1",src="192.168.2.1")/UDP(dport=27095,sport=27095)/Raw(load='aaaa'),iface=IFACES.dev_from_index(6))
{quote}

**Comment by gdsel** [comment] 2017-08-17 16:58
@stryngs and @gpotter2 
And I see two copies when Wireshark is capturing on the same interface that I call sendp()

I tried again with Wireshark monitoring a different NIC than the NIC that scapy is transmitting on. In this case I only see one copy of the frame.

I ran another experiment where I had two instances of Wireshark. One Wireshark instance monitored the interface that I was calling sendp() on and the other instance monitored the other interface. The Wireshark instance that monitored the sendp() interface observed two copies while the other Wireshark instance only observed a single copy.

**Comment by gpotter2** [comment] 2017-08-17 18:17
@gdsel While using the same interface, it's quite normal that you get the frame twice too.

What networking API have you installed ?
(Winpcap, Npcap...) ?
If Winpcap, could you uninstall it, delete 'Packet.dll' and 'wpcap.dll' from `C:/Windows/System32/` then install the latest version of Npcap ?

**Comment by stryngs** [comment] 2017-08-22 03:13
@gpotter2 Yes,  I have two NICs which I used for verification.  sendp() on 802.11 in monitor mode truly only sends one frame.  Try it for yourself.

**Comment by gpotter2** [comment] 2017-08-23 15:09
This "issue" only appears on monitor mode, but Isn't this the normal behavior ?

I do agree with @p-l- 
https://github.com/secdev/scapy/issues/724#issuecomment-321534038

> @stryngs I suppose in your specific case that the packet is seen when you send it, and, since you are in monitor mode it is also received. The sent packet has no Padding layer, which is added by the driver, and the received packet has it.

I'm pretty sure that if you turn off Monitor Mode in wireshark's options, you won't see the double packets in it...

**Comment by guedou** [comment] 2018-01-09 09:00
Closing this issue how Scapy is involved.

**Closed by guedou** 2018-01-09 09:00 UTC

**Comment by stryngs** [comment] 2018-01-10 05:52
Yes, I agree that this is a Monitor Mode issue; I believe I might have a solution so as to patch scapy and not have to deal with the double frames, but I'll deal with that as it comes.  Either way, good feedback on this Issue!

**Comment by randomshell** [comment] 2018-11-12 18:39
Hello, same issue here.

Code used for sending:
```
text = "hi"
a = IP(src="192.168.0.3", dst="127.0.0.1")/TCP(sport=RandShort(dport=1234)/Raw(load=text)
send(a)

```
Code used for sniffing, where the same packet is displayed twice:
```
sniff(filter="tcp port 1234", prn=lambda x:x.summary())
```
Tested on Fedora 28, both python 2.7 and python3.6, scapy 2.4.0. I don't think it's an issue on our side.
As it is, it's unusable for me.

Thank you in advance.

**Comment by p-l-** [comment] 2018-11-13 09:11
@randomshell please open new issues instead of commenting on closed (and probably unrelated) issues. This issue is related to `sendp()` with a Wlan monitor interface.
