### ISSUE TITLE
Updating from 2.3.2 to 2.3.3 breaks pyrit ('BitEnumField' object has no attribute 'names')

### ISSUE THREAD

**Issue by bacondropped** [secdev/scapy#323] opened 2016-11-01 06:43 UTC
I've updated scapy from 2.3.2 to 2.3.3 on my Manjaro (basically just Arch) installation a week ago, which broke Arch's `pyrit`. Long story short, apparently this update removed the `names` property from scapy's `BitEnumField`. I was also able to reproduce this issue with current masters for both scapy (2.3.3.dev5) and pyrit (0.5.1) on a fresh Arch VM.

Here's the trace for pyrit:
```
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 115, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 163, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 912, in attack_passthrough
    ap = self._fuzzyGetAP(self._getParser(capturefile), bssid, essid)
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 179, in _getParser
    parser.parse_pcapdevice(dev)
  File "/usr/lib/python2.7/site-packages/cpyrit/pckttools.py", line 601, in parse_pcapdevice
    self.parse_packet(pckt)
  File "/usr/lib/python2.7/site-packages/cpyrit/pckttools.py", line 614, in parse_packet
    if dot11_pckt.isFlagSet('type', 'Control'):
  File "/usr/lib/python2.7/site-packages/cpyrit/pckttools.py", line 66, in isFlagSet
    return (1 << field.names.index([value])) & self.__getattr__(name) != 0
AttributeError: 'BitEnumField' object has no attribute 'names'
```

Question: is this a breaking API change in scapy, in which case pyrit needs to be updated, or a bug in scapy, in which case this issue becomes a bug report? If the former is true, I'd also appreciate a pointer to an alternative API.

Package webpage here: https://www.archlinux.org/packages/community/x86_64/pyrit/.

The pyrit issue report can be found here: https://github.com/JPaulMora/Pyrit/issues/500.

**Comment by p-l-** [comment] 2016-11-01 11:00
The problem is that `pyrit`'s code relies on `isinstance(field, EnumField)`.

To have working `slots` with the `*EnumField`s, we had to create a dumb subclass `_EnumField` and other `*EnumField`s inherit from `_EnumField` rather than `EnumField`. With newer Scapy versions, the test in `pyrit` should be `isinstance(field, _EnumField)`.

I'm closing this one, feel free to re-open in if need be.

**Closed by p-l-** 2016-11-01 11:00 UTC

**Comment by bacondropped** [comment] 2016-11-03 07:52
That seems to work, thanks!

**Comment by Susan-Susan** [comment] 2016-12-24 06:40
Same error from pyrit here.
But would the solution be for today?

**Comment by p-l-** [comment] 2016-12-24 09:23
@Susan-Susan  you'll have to update Pyrit to get a version that includes the patch from JPaulMora/Pyrit#501, or manually apply this patch.

**Comment by Susan-Susan** [comment] 2016-12-24 20:52
Each link I visit just leads me to another link.
Do I download something?  (Specifically what?)
Do I edit something?  (Specifically what?)
Do I downgrade something?   (How?  Where?)
Do I run apt-get with some (unknown) options?    I'm lost here.

**Comment by p-l-** [comment] 2016-12-25 00:25
@Susan-Susan I'm sorry you're lost, I was just trying to help, so let me clarify this for you: this issue has been fixed in Pyrit, so you have to figure out how you update Pyrit.
I don't know who redirected you here in the first place, but there is nothing people here can do to help you, apart from redirecting you to the Pyrit project.

**Comment by Susan-Susan** [comment] 2016-12-25 02:57
I ended up here after finding so many people were also having Pyrite give exactly the same error.
No one here knows how to update a program in Linux?
How would you update ANY program?   Perhaps I can use a similar method.
I visit the Pyrit site and they just say "it's already fixed"... but also have no idea on how to actually get/download/edit/install/update Pyrit.   It's apparently just "fixed" but no one can actually use it.  (Linux has been a confusing/complete nightmare for everyone at our company.  Even the simplest of things break and never get fixed.  We just leave them broken forever... and move on to some other work-around instead.)

**Comment by p-l-** [comment] 2016-12-25 10:42
@Susan-Susan people probably know how to update a program in Linux, but this is **Scapy** bug tracker, not a Linux beginners help forum.

For the record, Scapy is not a Linux program, it works under Linux, *BSD, MacOS & Windows.

If you are using Linux and "Linux has been a confusing/complete nightmare for everyone at [your] company", well, I don't know, maybe you should hire someone who knows how to update a program?

**Comment by strasharo** [comment] 2016-12-25 12:55
For the folks using Kali, I submitted a defect here:
https://bugs.kali.org/view.php?id=3801

**Comment by bacondropped** [comment] 2016-12-25 19:23
> Even the simplest of things break and never get fixed

Yeah, Linux tends to do that; generally, you want to have a tech savvy person around if you use it. Anyway, please refer to [JPaulMora/Pyrit#500](https://github.com/JPaulMora/Pyrit/issues/500#issuecomment-269133793) for the update instructions.
