### ISSUE TITLE
Question: Looking for the equivalent of two calls in the latest version of scapy?

### ISSUE THREAD

**Issue by Tylous** [secdev/scapy#852] opened 2017-09-29 18:48 UTC
Hello, I am trying to update something to make it compatible with the latest version of scapy however I am running into issues. In older version I could call [Dot11Common].Antsignal and pkt.dBm_AntSignal to get the signal level of a 802.11 packet but with the latest version, these options appear to no longer be available . I was wondering if someone could point me to the alternative?

**Comment by p-l-** [comment] 2017-09-30 15:47
Hi,

The `Dot11Common` layer is part of a contribution module. You must load it (using `load_contrib('ppi_cace')`). Could you provide the exact code and the Scapy version you were using?

**Comment by Tylous** [comment] 2017-10-02 00:34
Below is the code and I was using Scapy 2.2.2 

```
	def Signal(self, pkt):
		global SIG
		if sw == '2':
			SIG = pkt[Dot11Common].Antsignal

		if sw == '1':
			SIG = str(pkt.dBm_AntSignal)
```
Could you point any documentation or reading material regarding load_contrib and ppi_cace. I am unsure how to integrate this change with the above code?

**Comment by p-l-** [comment] 2017-10-03 11:23
Could you also provide the `import` statements used for scapy, and the `load_{contrib,layer,module}` calls?

**Comment by Tylous** [comment] 2017-10-03 19:43
That worked for Dot11Common but I am still having issues with dBm_AntSignal, could you please provide with the alternative to dBm_AntSignal?

**Comment by p-l-** [comment] 2017-10-03 20:41
Can you please answer my question, so that we can try to help you?

**Comment by Tylous** [comment] 2017-10-03 20:45
Sure they are:
`logging.getLogger("scapy.runtime").setLevel(logging.CRITICAL)`
`from scapy.all import *`
and
`load_contrib('ppi_cace')`

**Comment by p-l-** [comment] 2017-10-04 16:23
I cannot reproduce with v2.2.0 nor v2.3.0 and there is no tag v2.2.2. Can you give the commit number or the archive?

**Comment by Tylous** [comment] 2017-10-04 16:25
I was using this version of scapy https://bitbucket.org/secdev/scapy-com

**Comment by p-l-** [comment] 2017-10-04 16:29
OK, that's the "community" version, and it contains features that never landed into the "main" version. You can submit a pull request if you need that code.

**Closed by p-l-** 2017-10-04 16:29 UTC
