### ISSUE TITLE
Example of sending ICMP is not working

### ISSUE THREAD

**Issue by luisreyna93** [secdev/scapy#1490] opened 2018-06-22 20:54 UTC
#### Brief description

< describe the main issue in one sentence >
I am trying to run the command specified in the demo about ICMP and it is not working
< if possible, describe what components / protocols could be affected by the issue (e.g. wrpcap() + IPv6, it is likely this also affects XXX) >
IP and ICMP
#### Environment

- Scapy version: < scapy version and/or commit-hash > 2.4.0
- Python version: < e.g. 3.5 > 2.7
- Operating System: < e.g. Minix 3.4 > Mac, 16.7.0 Darwin Kernel

< if needed - further information to get a picture of your setup (e.g. a sketch of your network setup) >
![scapyerr](https://user-images.githubusercontent.com/6774952/41798763-c25ddd74-7623-11e8-8692-16247f6ea0fd.png)

#### How to reproduce
Instal version 2.4 and run : p = sr1(IP(dst="www.slashdot.org")/ICMP()/"XXXXXXXXXXX")

**Comment by gpotter2** [comment] 2018-06-22 21:07
May be a problem of your firewall, or a OS restriction when the ICMP packets are not well built: working well for me

![image](https://user-images.githubusercontent.com/10530980/41799229-f9276d46-7670-11e8-80ca-81d52fbea5fd.png)

**Comment by p-l-** [comment] 2018-06-23 07:17
You may have a firewall preventing you from sending ICMP echo request packet to `www.slashdot.org`. Could you try, from the same computer & using the same connection, to run `ping -c 4 www.slashdot.org` from the command line and report the result here?

**Comment by luisreyna93** [comment] 2018-06-25 16:18
Hi
This is the output of the ping : 

64 bytes from 216.105.38.15: icmp_seq=1 ttl=37 time=32.2 ms                                                                                               
64 bytes from 216.105.38.15: icmp_seq=2 ttl=37 time=32.2 ms                                                                                               
64 bytes from 216.105.38.15: icmp_seq=3 ttl=37 time=32.2 ms                                                                                               
64 bytes from 216.105.38.15: icmp_seq=4 ttl=37 time=32.3 ms

4 packets transmitted, 4 received, 0% packet loss, time 3035ms

Also I ran the same example command at the same time I ran tcpdump command and tcpdump is getting the response but scapy is not.

**Comment by rot0xd** [comment] 2018-08-27 17:02
I had the same issue. I was able to get around it by specifying the "id" field in the ICMP header. This, for some reason, was not autogenerated by scapy. Below is the output of my test:

```
In [4]: sr1(IP(dst="10.64.45.1")/ICMP())
Begin emission:
Finished sending 1 packets.
.......^C
Received 7 packets, got 0 answers, remaining 1 packets

In [5]: sr1(IP(dst="10.64.45.1")/ICMP(id=100))
Begin emission:
Finished sending 1 packets.
.*
Received 2 packets, got 1 answers, remaining 0 packets
Out[5]: <IP  version=4 ihl=5 tos=0x0 len=28 id=1 flags= frag=0 ttl=250 proto=icmp chksum=0x77c7 src=10.64.45.1 dst=10.91.7.125 options=[] |<ICMP  type=echo-reply code=0 chksum=0xff9b id=0x64 seq=0x0 |>>
```

**Comment by guedou** [comment] 2018-08-27 18:48
What are you OS, Python, and Scapy versions?

**Comment by rot0xd** [comment] 2018-08-27 18:56
**OS:** Fedora 27
**Python:** 3.6.6
**Scapy:** 2.40

I was able to reproduce this on Arch using python 3.7 with Scapy 2.40 as well. 

I was unable to reproduce it on my CentOS 6 using python 3.4.8 and Scapy 2.40  as omitting the ID field worked as intended.

**Comment by guedou** [comment] 2018-08-27 19:27
What is the OS of the target?

The default ICMP id value seems to work fine, see
```
In [2]: sr1(IP(dst="8.8.8.8")/ICMP())
Begin emission:
..Finished sending 1 packets.
*
Received 3 packets, got 1 answers, remaining 0 packets
Out[2]: <IP  version=4 ihl=5 tos=0x0 len=28 id=46219 flags= frag=0 ttl=121 proto=icmp chksum=0x9295 src=8.8.8.8 dst=192.168.42.8 options=[] |<ICMP  type=echo-reply code=0 chksum=0x0 id=0x0 seq=0x0 |>> 
```

**Comment by rot0xd** [comment] 2018-08-27 19:46
The target used in the test is a Cisco Router.

The following are packets being sent by Scapy. The first image is without the ID field being specified. It does not receive a reply. The second is given an ID of "12345". The reply comes back immediately.

![no_id](https://user-images.githubusercontent.com/5566061/44682020-150d2780-a9f7-11e8-820b-6a84d9cfdb70.png)

---

![id](https://user-images.githubusercontent.com/5566061/44682026-176f8180-a9f7-11e8-975c-49ae775d3640.png)


Should Scapy be autogenerating a packet ID?

**Comment by guedou** [comment] 2018-08-27 19:54
That is likely a correct fix. What is the IOS version? I never met such behavior.

**Comment by rot0xd** [comment] 2018-08-27 20:00
This was very educational for me.... I never knew about [this](https://www.paloaltonetworks.com/documentation/80/pan-os/web-interface-help/network/network-network-profiles-zone-protection/packet-based-attack-protection/icmp-drop) [behavior](https://kb.juniper.net/InfoCenter/index?page=content&id=KB8342) in firewalls.

I would assume this is what is causing our packets to be dropped. If this is something that will be commonplace in major firewall manufacturers, is defaulting to a random ID a valid feature request?

**Comment by gpotter2** [comment] 2018-08-27 21:33
@guedou Should we put 1 as default instead of 0 ?

**Comment by rot0xd** [comment] 2018-08-27 21:45
Apparently the iputil `ping` binary [uses it's PID as the ID](https://github.com/iputils/iputils/blob/master/ping.c#L972) field. This seems like a sane default with little risk of having to modify in the future.

**Comment by guedou** [comment] 2018-08-28 08:27
RandShort() might be a better alternative.

On the other hand, I really wonder if this is a bug in Scapy. ‘0’ works fine except against this specific implementation. I don’t believe that this should be fixed.

**Comment by ineffectivecoder** [comment] 2018-08-28 15:05
I'm more curious as to why Scapy sends 0 as the identifier. As mentioned above there are a few enterprise grade firewalls that have protections to block ICMP with ID=0 specifically. I've yet to find the reasoning why you would ever use 0 in the first place, and why the firewalls have specific rules for blocking it.

**Comment by gpotter2** [comment] 2018-08-28 15:55
That’s pretty easy, we just default all our non-required fields to 0
https://github.com/secdev/scapy/blob/master/scapy/layers/inet.py#L720

**Comment by guedou** [comment] 2018-09-22 18:27
I am closing this issue since this is not related  to Scapy.

**Closed by guedou** 2018-09-22 18:27 UTC
