### ISSUE TITLE
Scapy AsyncSniffer can miss packets when many are sent

### ISSUE THREAD

**Issue by Kkevsterrr** [secdev/scapy#2608] opened 2020-04-24 03:54 UTC
#### Brief description

The AsyncSniffer can miss packets under load.

I have reproduced this on 2.4.3, and the latest build (as suggested in the Github template with `pip install --upgrade git+git://github.com/secdev/scapy`)

#### Environment

-   Scapy version: `2.4.3`, also reproduced on `2.4.3.dev494`
-   Python version: `3.5.2`
-   Operating System: `Ubuntu 16.04 LTS`

I am using scapy for some small experiments on a gigabit link. 

#### How to reproduce

I can reproduce this by simply creating and starting an AsyncSniffer with a custom callback & an IP filter.

```
from scapy.all import *

count = 0
def process_packet(pkt):
    """
    Handles inbound packest
    """
    global count
    print(pkt.summary())
    count += 1

ip = "<SOURCE_IP_HERE>"
sniffer = AsyncSniffer(prn=process_packet, filter='src %s' % ip, store=False)
sniffer.start()
```

If I send this machine more than about 75 packets very quickly (<0.01s), scapy starts just missing packets. Using tcpdump with the exact same filter, I see all of the packets I expect, but they do not show up in scapy. Sending it 85 packets, it captures 62. Sending 125, it gets 80. There does not appear to be rhyme or reason to which packets scapy misses.

The `store` flag does not seem to have any effect on this. 

#### Actual result

`process_packet` does not get called with all of the packets it should. 

#### Expected result

Scapy should capture all of the packets that match the filter.

**Comment by polybassa** [comment] 2020-04-24 05:25
Hi, thanks for this report.

Does your code still fail, if you don't print inside process_packet?
For example, just copy the packet into a list.

**Comment by gpotter2** [comment] 2020-04-24 11:39
This is a known issue: scapy doesn't handle heavy loads very well because we process packets too slowly, and the buffer fills up.

I have a few tricks up my sleeves, for instance you can disable the dissection of all layers you do not use using something like https://github.com/gpotter2/scapy/commit/0b85216fba827106b81cb91fdd6316e3b3c0537d and `conf.layers.filter([Ether, IP])` for instance. (PR soon..)

**Comment by Kkevsterrr** [comment] 2020-04-24 12:24
Okay, that is good to know - thanks for the heads up. 

Is there a way to increase that buffer size? I’m more interested in accuracy over speed right now - if it takes scapy time to process, that’s okay as long as it captures the traffic.

Yes, it still fails if I remove the print (I actually found this issue just by examining packet counts, and added the print later to verify).

**Comment by Kkevsterrr** [comment] 2020-04-24 12:52
Is this the BPF buffer in supersocket.py?

**Comment by fe64970103** [comment] 2020-04-27 19:52
I can confirm the same with the sniff function. I'm sniffing WIFI traffic in particular management packets where I'm following the connection sequence of a device to the AP. Scapy misses packets a lot, up to a degree that the solution is not usable for me as I can't afford to miss management packets. Well, here and there missing some would be still acceptable, but the loss I'm facing is like 1/3 of the packets. For instance running tcpdump in parallel I can see all of the packets of interest.

Any hits or dirty workarounds around this?

**Comment by gpotter2** [comment] 2020-04-28 05:50
A workaround is to use a very strict filter. (using `filter`).
That way we let the kernel deal with the heavy traffic and scapy only gets a small part of it.

**Comment by fe64970103** [comment] 2020-04-28 06:45
Gabriel, indeed I manually pasted your [commit ](https://github.com/gpotter2/scapy/commit/0b85216fba827106b81cb91fdd6316e3b3c0537d) in my codebase and it seems to help a lot.

What is interesting that running Scapy with no filter I get a CPU load of around 50%. That being said the packet loss seems more buffer related than a CPU bottleneck. Can you pinpoint me where things get buffered so I can play with the buffer a bit? Thanks.

**Comment by gpotter2** [comment] 2020-04-28 11:21
If you're on linux you might also get better results by increasing `conf.bufsize`

**Comment by fe64970103** [comment] 2020-04-29 08:15
I've tried it by increasing the buffer size 10x, but there is not a whole big difference. Instead I've tried something else. I tried to go on a relatively clean channel on a network that has no clients, but just the one I'm exercising with. Still the management packets are missing. 

In particular I'm sending a packet out (Dot11Auth) from within the sniff() callback and then I'm expecting the main AP to reply with another Dot11Auth packet, but scapy doesn't catch it.

I'm wondering if sending the packet from within the callback that blocks everything to a degree scapy misses it. Should I be sending from another thread maybe?

**Comment by py2010** [comment] 2020-04-30 03:21
can use pcap and asyncio
```
import pcap  # cython
import asyncio  # py3.5+
from scapy.all import *
conf.use_pcap = True
......
pcap threading:  p.loop(0, func)
scapy coroutine: pkt=Ether(pcap_packet)
session.on_packet_received(pkt)
......
```
Reference
scapy.sendrecv.AsyncSniffer._run()
```
while sniff_sockets and self.continue_sniff:
    ......
    session.on_packet_received(p)
```

**Comment by gpotter2** [comment] 2020-05-18 13:05
I marked your comment as spam because I don't understand a word of it. It just seems like random code with no context.

**Comment by gpotter2** [comment] 2020-05-20 12:17
I'll consider this closed by https://github.com/secdev/scapy/pull/2642
See https://scapy.readthedocs.io/en/latest/usage.html#performance-of-scapy

**Closed by gpotter2** 2020-05-20 12:17 UTC
