### ISSUE TITLE
filter doesn't directly apply while sniffing

### ISSUE THREAD

**Issue by Xavier59** [secdev/scapy#332] opened 2016-11-06 15:00 UTC
While starting to sniff, I noticed that the filter doesn't directly apply to the first 2-3 packets which lead to call the prn function without respecting the filter. I havn't take a look to the scapy source but it feels to me like this bug could be caused by an asynchronous call.

**Comment by p-l-** [comment] 2016-11-06 15:56
Duplicate of #55.

**Closed by p-l-** 2016-11-06 15:56 UTC
Labels: duplicate
