### ISSUE TITLE
should_handle_ServerCertificate AttributeError: 'readConnState' object has no attribute 'key_exchange'

### ISSUE THREAD

**Issue by r4t31** [secdev/scapy#3138] opened 2021-03-15 17:06 UTC
I use scapy version 2.4.4 and got an error running this code:

```python

from scapy.layers.tls.all import *

class ModifiedTLSClientAutomaton(TLSClientAutomaton):
    @ATMT.condition(TLSClientAutomaton.PREPARE_CLIENTFLIGHT1)
    def should_add_ClientHello(self):
        if self.client_hello:
            p = self.client_hello
        else:
            p = TLSClientHello()
        self.add_msg(p)
        raise self.ADDED_CLIENTHELLO()

# TLS Version
version = "1.2"

ciphers =  [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384]
ciphers += [TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256]
ciphers += [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384]
ciphers += [TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256]

compression='null'
ext3 = TLS_Ext_SupportedEllipticCurves(groups=['secp256r1','secp384r1','brainpoolP256r1','brainpoolP384r1','brainpoolP512r1'])
ext4 = TLS_Ext_SupportedPointFormat(ecpl='uncompressed')
ext5 = TLS_Ext_SignatureAlgorithms(sig_algs=['sha256+ecdsa','sha384+ecdsa','sha512+ecdsa'])

ext = [ext3, ext4, ext5]

ch = TLSClientHello(ciphers=ciphers, ext=ext, comp=compression)
ch.show()
t = ModifiedTLSClientAutomaton(client_hello=ch, server="192.168.0.1", dport=443)
t.run()
```

error log:
```
Traceback (most recent call last):
  File "C:\Users\ratel\test_scapy\test.py", line 64, in <module>
    t.run()
  File "C:\Users\ratel\test_scapy\venv\lib\site-packages\scapy\automaton.py", line 995, in run
    six.reraise(c.exc_info[0], c.exc_info[1], c.exc_info[2])
  File "C:\Users\ratel\test_scapy\venv\lib\site-packages\scapy\modules\six.py", line 697, in reraise
    raise value
  File "C:\Users\ratel\test_scapy\venv\lib\site-packages\scapy\automaton.py", line 841, in _do_control
    state = next(iterator)
  File "C:\Users\ratel\test_scapy\venv\lib\site-packages\scapy\automaton.py", line 890, in _do_iter
    self._run_condition(cond, *state_output)
  File "C:\Users\ratel\test_scapy\venv\lib\site-packages\scapy\automaton.py", line 784, in _run_condition
    cond(self, *args, **kargs)
  File "C:\Users\ratel\test_scapy\venv\lib\site-packages\scapy\layers\tls\automaton_cli.py", line 356, in should_handle_ServerCertificate
    if not self.cur_session.prcs.key_exchange.anonymous:
AttributeError: 'readConnState' object has no attribute 'key_exchange'
```

**Comment by gpotter2** [comment] 2021-04-13 12:33
Hi, thanks for the report & sorry for the delay.
What are you using as a server? It would be useful to be able to reproduce this. Thanks

**Comment by guedou** [comment] 2021-10-02 11:32
I am closing this issue due to no answer.

@r4t31 if you can share a way to reproduce this issue, we will reopen it and investigate.

**Closed by guedou** 2021-10-02 11:32 UTC
Labels: tls
