### ISSUE TITLE
Install via pip3 on raspberry pi errors about missing LICENSE

### ISSUE THREAD

**Issue by pvcraven** [secdev/scapy#1864] opened 2019-02-22 21:08 UTC
#### Brief description

Install via pip3 on raspberry pi fails with error about missing LICENSE file

#### Environment

-   Scapy version: 2.4.2
-   Python version: 3.7
-   Operating System: Linux raspberrypi 4.14.79-v7+

#### How to reproduce

Run `sudo pip3 install scapy` on a raspberry pi.

#### Actual result
```
  copying build/scripts-3.5/UTscapy -> build/bdist.linux-armv7l/wheel/scapy-2.4.2.data/scripts
      copying build/scripts-3.5/scapy -> build/bdist.linux-armv7l/wheel/scapy-2.4.2.data/scripts
      changing mode of build/bdist.linux-armv7l/wheel/scapy-2.4.2.data/scripts/UTscapy to 755
      changing mode of build/bdist.linux-armv7l/wheel/scapy-2.4.2.data/scripts/scapy to 755
      error: [Errno 2] No such file or directory: 'LICENSE'

      ----------------------------------------
      Failed building wheel for scapy
      Running setup.py clean for scapy
    Failed to build scapy
    Installing collected packages: scapy
      Running setup.py install for scapy ... done

```

**Comment by gpotter2** [comment] 2019-02-22 22:01
Thanks for the report, you'll notice that it doesn't technically fail, because of a PyPi fallback.

This issue a duplicate of https://github.com/secdev/scapy/issues/1783 which was fixed in https://github.com/secdev/scapy/pull/1784

**Closed by gpotter2** 2019-02-22 22:01 UTC

**Comment by nanduraj1** [comment] 2019-03-28 11:08
Hi, I'm facing the same error. Waiting for fix in pip..

**Comment by gpotter2** [comment] 2019-03-28 11:32
You can use `pip install --pre scapy` in the mean time
