### ISSUE TITLE
Scapy cannot sent packet to own IP address

### ISSUE THREAD

**Issue by cswarnan** [secdev/scapy#561] opened 2017-03-15 19:14 UTC
Hi 
I am using scapy 2.3.3. 
I a trying to send packet to my own IP address. 

For ex. my machine IP = 192.168.21.133
ans,unans = sr(IP(dst="192.168.21.133") / TCP())
ans.show()

I am getting error :
ERROR: --- Error sending packets
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 374, in sndrcv
    pks.send(p)
  File "C:\Python27\lib\site-packages\scapy\arch\pcapdnet.py", line 239, in send
    ifs = dnet.ip()
  File "dnet.pyx", line 250, in dnet.ip.__init__ (./dnet.c:2702)
OSError: No such file or directory

I am on wired network. 
Please help

**Comment by gpotter2** [comment] 2017-03-18 22:37
Please close this, duplicate of https://github.com/secdev/scapy/issues/562

**Closed** 2017-03-19 12:16 UTC
