### ISSUE TITLE
'L2Socket' object has no attribute 'nonblock_recv'

### ISSUE THREAD

**Issue by samorris** [secdev/scapy#1615] opened 2018-09-27 15:03 UTC
#### Brief description

AttributeError: 'L2Socket' object has no attribute 'nonblock_recv'

#### Environment

- Scapy version: a35575ff22da176a8b515405faea9a689462da0c (25 September 2018)
- Python version: 2.7..15
- Operating System: Fedora 27

#### How to reproduce

The problem occurred when running some custom code written round Scapy.  However, the problem appears to lie in Scapy itself rather than the code, as the traceback received was:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "v4d.py", line 257, in genDiscover
    offer = exchange (discover)
  File "v4d.py", line 442, in exchange
    ans,uns = srp(request, iface = src_iface, timeout = time_out)
  File "/home/stephen/scapy/scapy/sendrecv.py", line 546, in srp
    result = sndrcv(s, x, *args, **kargs)
  File "/home/stephen/scapy/scapy/sendrecv.py", line 258, in sndrcv
    _storage_policy=_storage_policy,
  File "/home/stephen/scapy/scapy/sendrecv.py", line 145, in _sndrcv_rcv
    r = _get_pkt()
  File "/home/stephen/scapy/scapy/sendrecv.py", line 124, in _get_pkt
    res = pks.nonblock_recv()
AttributeError: 'L2Socket' object has no attribute 'nonblock_recv'
```

#### Fix

The following patch fixed the issue for me:
```
diff --git a/scapy/sendrecv.py b/scapy/sendrecv.py
index 0efe2f36..81dec720 100644
--- a/scapy/sendrecv.py
+++ b/scapy/sendrecv.py
@@ -117,7 +117,7 @@ def _sndrcv_rcv(pks, hsent, stopevent, nbrecv, notans, verbose, chainCC,
             return pks.recv()
     elif (conf.use_pcap
           and not isinstance(pks,
-                             (StreamSocket, L3RawSocket, L2ListenTcpdump))) \
+                             (StreamSocket, L3RawSocket, L2Socket, L2ListenTcpdump))) \
         or (not isinstance(pks, (StreamSocket, L2ListenTcpdump))
             and (DARWIN or FREEBSD or OPENBSD)):
         def _get_pkt():
```
I've not submitted this as a formal pull request as I don't know whether it just fixes the underlying issue or just a particular manifestation of it.

**Comment by guedou** [comment] 2018-09-27 15:33
Could you provide a small example that triggers the issue? It will help us reproducing the issue.

**Comment by samorris** [comment] 2018-09-27 17:17
OK.  I've trimmed down the code to more or less the minimum. The attached ZIp archive 

[v4d.py.zip](https://github.com/secdev/scapy/files/2425058/v4d.py.zip)

contains one file, v4d.py.  Edit lines 5-7 to set the name, MAC address and IPv4 address of an interface on your system.  Run Scapy using sudo and issue the following commands:

```
execfile('v4d.py')   # To load the file
genDiscover('foo')   # To trigger the problem
```

Be aware that the code sends a DHCP DISCOVER packet to the network.  As it doesn't follow up any received OFFER with a REQUEST, it shouldn't interfere with any DHCP set-up you may have.

**Comment by guedou** [comment] 2018-09-27 18:12
Thanks. Could your provide a smaller example?

**Comment by samorris** [comment] 2018-09-27 19:27
After some more work, I've reduced it to the following:

```
import subprocess
import binascii

# Set this to the interface to be used, its MAC and the IPV4 address
# associated with it.
iface_name = "ens38"
iface_mac = "00:30:56:24:9c:2a"
iface_ip = "172.16.228.30"

# Setting this to False makes the error go away.
conf.use_pcap = True

src_mac = binascii.unhexlify(iface_mac.replace(':', ''))
options = [("message-type","discover"), "end"]

discover = Ether(src = src_mac, dst = "ff:ff:ff:ff:ff:ff")
discover /= IP(src = iface_ip, dst = "255.255.255.255")
discover /= UDP(sport = 68, dport = 67)
discover /= BOOTP(chaddr = src_mac, xid = 1, secs = 0)
discover /= DHCP(options = options)

srp(discover, iface = iface_name, timeout = 2)
```
I also made the discovery that it is the "conf.use_pcap" statement (used elsewhere in the larger program) that triggers the problem.  With it set to False, the problem does not appear.

**Comment by guedou** [comment] 2018-09-28 14:46
Thanks!

On Linux, `conf.use_pcap` is not needed unless you install one the of the many pcap Python modules. Here, you are hitting a corner case where Scapy configures itself and then you ask it to use pcap based sockets. It is not yet able to detect this corner case.

I will evaluate your fix, and propose a PR.

**Comment by grace-grimwood** [comment] 2018-12-10 03:08
Hey, I have the same issue on v2.4.0, running on Python 2.7.15rc1 on an Ubuntu Server 18.04 LTS VM, and it looks to me like the cause is that the conditional at [sendrecv.py:96](https://github.com/secdev/scapy/blob/v2.4.0/scapy/sendrecv.py#L96) is assuming that `conf.L2socket` is type `L2pcapSocket` from [`scapy.arch.pcapdnet`](https://github.com/secdev/scapy/blob/v2.4.0/scapy/arch/pcapdnet.py#L249), but that class is only created when `conf.use_winpcapy` is True, which only ever happens on Windows, and as such cannot be true for the given OSes in sendrecv.py (`DARWIN`, `FREEBSD`, `OPENBSD`). In fact, on Ubuntu, `conf.L2socket` is an instance of the class `L2Socket` from [`scapy.arch.linux`](https://github.com/secdev/scapy/blob/v2.4.0/scapy/arch/linux.py#L498), as the original libpcap library cannot send (from what I understand, anyway), but Npcap and WinPcap both feign this behaviour.

Anyway, hope this helps!

**Comment by gpotter2** [comment] 2018-12-10 17:16
Hi @grace-grimwood,

Could you retry using the latest dev version: https://github.com/secdev/scapy/archive/master.zip

We have recently completly refactored the part choosing the read function, for instance the line you quoted is now https://github.com/secdev/scapy/blob/master/scapy/sendrecv.py#L90

**Comment by grace-grimwood** [comment] 2018-12-10 20:21
@gpotter2 I am unable to use the dev version due to a breaking bug in scapy.arch.pcapdnet, which I have reported here (#1731). It's difficult to tell if the issue is still present in the dev version, as I keep getting segfaults.

**Comment by p-l-** [comment] 2018-12-11 21:37
@grace-grimwood can you pull the current dev version? A fix from @gpotter2 for #1731 has been merged.

**Comment by grace-grimwood** [comment] 2018-12-12 23:16
@p-l- Sure, but I'm moving PCs today, so I'll give it a shot tomorrow.

**Comment by guedou** [comment] 2019-01-11 15:58
I could not reproduce the issue on Ubuntu 18.04.

Please reopen the issue if you can help us reproduce it.

**Closed by guedou** 2019-01-11 15:58 UTC

**Comment by this-is-r-gaurav** [comment] 2019-02-23 17:10
Does the pip still have this issue, i downloaded it with pip but throwing same error
