### ISSUE TITLE
Bug: unable to build layer when have Conditonal ByteField after BitFields when total bits % 8 !=0

### ISSUE THREAD

**Issue by Crossfire55555** [secdev/scapy#756] opened 2017-08-09 19:22 UTC
Hard to explain but here it goes. If you make a protocol which uses bitfields  which leaves a tuple in the string of the packets and then transition into a conditional bytefield then scapy throws an error.

Example:
```python
class FAB_HDR(Packet):
     name = "FAB_HDR "
     fields_desc = [ BitField("PType", 0 , 5),
                    ConditionalField(ByteField("Subtype", 0)
                        ,lambda p:p.PType != 13),
                    ConditionalField(ByteField("Subtype", 0)
                        ,lambda p:p.PType == 13),
                    BitField("Mask_Flags", 0, 3)
                         ]
```
Will result in this output 
>>> a= FAB_HDR2()
>>> a.show2()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 1066, in show2
    return self.__class__(str(self)).show(dump, indent, lvl, label_lvl, rawfmt)
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 312, in __str__
    return self.build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 410, in build
    p = self.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 392, in do_build
    pkt = self.self_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 373, in self_build
    p = f.addfield(self, p, val)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 150, in addfield
    return self.fld.addfield(pkt,s,val)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 75, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
TypeError: can only concatenate tuple (not "str") to tuple

Now make the the change to BitField of length 8 and you get this
```python
class FAB_HDR(Packet):
     name = "FAB_HDR "
     fields_desc = [ BitField("PType", 0 , 5),
                    ConditionalField(BitField("Subtype", 0, 8)
                        ,lambda p:p.PType != 13),
                    ConditionalField(BitField("Subtype", 0, 8)
                        ,lambda p:p.PType == 13),
                    BitField("Mask_Flags", 0, 3)
                         ]
```
>>> a= FAB_HDR2()
>>> a.show2()
###[ FAB_HDR2  ]###
  PType= 0
  Subtype= None
  Mask_Flags= 0

Also note that subtype is None when it should be 0

Now with no conditionals 
```python 
class FAB_HDR2(Packet):
     name = "FAB_HDR2 "
     fields_desc = [ BitField("PType", 0 , 5),
                     ByteField("Subtype", 0),
                     BitField("Mask_Flags", 0, 3)
                   ]
```
>>> a= FAB_HDR2()
>>> a.show2()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 1066, in show2
    return self.__class__(str(self)).show(dump, indent, lvl, label_lvl, rawfmt)
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 312, in __str__
    return self.build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 410, in build
    p = self.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 392, in do_build
    pkt = self.self_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 373, in self_build
    p = f.addfield(self, p, val)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 75, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
TypeError: can only concatenate tuple (not "str") to tuple

Now with BitField 
```python 
class FAB_HDR2(Packet):
     name = "FAB_HDR2 "
     fields_desc = [ BitField("PType", 0 , 5),
                     BitField("Subtype", 0, 8),
                     BitField("Mask_Flags", 0, 3)
                   ]
```

>>> a= FAB_HDR2()
>>> a.show2()
###[ FAB_HDR2  ]###
  PType= 0
  Subtype= 0
  Mask_Flags= 0

Just thought I would let you guys know. It took me about an hour to figure it out so hopefully this can save someone some time.

**Comment by p-l-** [comment] 2017-08-10 14:48
Hi,

Thanks for this report. Your title is confusing since, as you show it, this is not related to the use of `ConditionalField`s.

It is not a bug, when you use `BitField`s, you must have a continuous total number of bits that is a multiple of 8, to create full bytes. The solution, as you mention it, is to use `BitField`s with length 8 to replace `ByteField`s.

If you feel like it, you can create a PR to document this. In the meantime, I'm closing this issue, feel free to re-open it if needed.

**Closed by p-l-** 2017-08-10 14:48 UTC

**Comment by jxmorris12** [comment] 2021-12-07 00:30
This is a serious gotcha! I think the error message could definitely be improved.
