### ISSUE TITLE
Scapy - Cannot send packet when source IP and and destination IP is same

### ISSUE THREAD

**Issue by cswarnan** [secdev/scapy#564] opened 2017-03-16 20:28 UTC
I am using latest code from github, getting message as below:

My source code is
data = "A"*1460
ans, un_ans = sr(IP(src="192.168.1.135", dst="192.168.1.135") / ICMP()/data)

I am using Windows 7 and Python27

Get-NetRoute : The term 'Get-NetRoute' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

Get-NetRoute -AddressFamily IPV6 | select ifIndex, DestinationPrefix, NextHop

CategoryInfo : ObjectNotFound: (Get-NetRoute:String) [], Comman
dNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
Get-NetRoute : The term 'Get-NetRoute' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

Get-NetRoute -AddressFamily IPV6 | select ifIndex, DestinationPrefix

CategoryInfo : ObjectNotFound: (Get-NetRoute:String) [], Comman
dNotFoundException
FullyQualifiedErrorId : CommandNotFoundException
Begin emission:
Finished to send 1 packets.
.............................................................................................................................................................................................

It does not send any packet and keep going with these ....
You then need to manually exit the program.

**Comment by gpotter2** [comment] 2017-03-18 22:36
Please close this, duplicate of https://github.com/secdev/scapy/issues/562

**Closed** 2017-03-19 12:17 UTC
