### ISSUE TITLE
sendrecv silently catching OSErrors by default

### ISSUE THREAD

**Issue by HorakS** [secdev/scapy#2407] opened 2020-01-13 08:41 UTC
The behaviour of sndrcv methods has changed quite a bit lately (due to the change to AsyncSniffers). 
Currently, AsyncSniffer's _run() method catches all Exceptions (in case of OSErrors they are not even logged, since they are listed as "allowed exceptions").

Most of our scripts rely on being able to catch these Exceptions in order to detect socket issues. Also I think it is generally very unintuitive that these Exceptions are caught when using a socket's sr methods, where the sniffer is running synchronously. What is your take on Exception handling within scapy?

A workaround in the current master branch is e.g. setting SuperSocket's read_allowed_exceptions to some dummy Exception and setting conf.debug_dissector to >= 2.

**Comment by gpotter2** [comment] 2020-01-13 15:13
> setting SuperSocket's read_allowed_exceptions to some dummy Exception 

This was supposed to do it, but it seems I left a placeholder instead of an actual dummy exception.

https://github.com/secdev/scapy/blob/f9311c2d2c65f09eedede08a347ee541f32c132e/scapy/sendrecv.py#L903

> in case of OSErrors they are not even logged, since they are listed as "allowed exceptions"

That's surprising.

> Also I think it is generally very unintuitive that these Exceptions are caught when using a socket's sr methods, where the sniffer is running synchronously. 

`sniff` is catching the exceptions because it is supposed to be able to support sniffing on multiple sockets at the same time. Whenever one crashes, it will discard it and continue to sniff on the others until either there are none left, either a stop condition is reached.

**However**, I agree that this isn't intuitive AND should be documented.

Although, I think setting `conf.debug_dissector` to 2 would be the expected behavior. Setting it to 1 displays packet dissection failures (which are hidden by default), and 2 raises exceptions.

What do you think ?

**Comment by HorakS** [comment] 2020-01-20 09:08
From the name `conf.debug_dissector` i would not have guessed that this setting is used to change scapy's exception handling. Maybe a separate variable or better naming would help here.

Other than that, i think this solution is acceptable, provided that `read_allowed_exceptions` is actually set to a dummy exception by default.

**Comment by Asmeble** [comment] 2021-08-14 22:31
this needs to be fixed immediately.

**Comment by gpotter2** [comment] 2024-02-03 18:24
Closing since `conf.debug_dissector = 2` fits here.

**Closed by gpotter2** 2024-02-03 18:24 UTC
Labels: discussion
