### ISSUE TITLE
[tests] "AS resolvers" test is very unstable

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#486] opened 2017-01-24 20:39 UTC
This test is crashing all the time... We should use another website/dns/server/method/test for it...
```

###(064)=[failed] AS resolvers
>>> ret = conf.AS_resolver.resolve("8.8.8.8", "8.8.4.4")
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "C:\projects\scapy\scapy\as_resolvers.py", line 107, in resolve
    res = ASres.resolve(*todo)
  File "C:\projects\scapy\scapy\as_resolvers.py", line 79, in resolve
    s.connect((self.server,self.port))
  File "C:\Python27-x64\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10061] No connection could be made because the target machine actively refused it

```

Samples of tests that crashed because of that in the last week:
https://ci.appveyor.com/project/p-l-/scapy/build/1.0.394
https://ci.appveyor.com/project/p-l-/scapy/build/1.0.404
https://travis-ci.org/gpotter2/scapy/jobs/194951969

**Comment by guedou** [comment] 2017-01-25 07:22
I have seen this error before.

The issue is not the target (8.8.8.8) but the fact that some builders seems unable to contact Whois servers or Whois TCP port. Travis networking is not reliable.

I think that it is better to leave the test and restart some Travis jobs when needed.

**Comment by gpotter2** [comment] 2017-01-25 12:30
https://github.com/secdev/scapy/pull/487
is quite relevent isn't it ? It retries when the test fails...

**Comment by guedou** [comment] 2017-01-25 12:32
I just merged it =)

**Closed** 2017-01-25 12:31 UTC
Labels: tests
